using System.ComponentModel.DataAnnotations;

namespace Netor.Cortana.Entitys
{
    /// <summary>
    /// Workflow 任务实体（OrchestrationTask 表）。
    /// 与 <see cref="ChatSessionEntity"/> 字段命名 / 含义对齐，UI 复用 ChatHistoryPanel 的列表 / 排序 / 置顶 / 归档代码模式。
    /// 详见 docs/未来版本策划/多智能体编排模式策划/06-工作模式独立模块设计.md §3.1。
    /// </summary>
    /// <remarks>
    /// 决策对齐：
    /// 6-A：Title 用户可空 + LLM 兜底（IsTitleAutoGenerated 持久化标志）；
    /// 7-A：列表对齐 Chat 风格（IsPinned / IsArchived / LastActiveTimestamp / TotalTokenCount）；
    /// 9-A：宿主重启后 running/paused/pending 一律标 failed（启动孤儿清理）；
    /// 10-A：复制为新任务（SourceTaskId 记录原任务）。
    /// </remarks>
    public class OrchestrationTaskEntity : BaseEntity
    {
        /// <summary>任务标题，与 ChatSession.Title 对齐（256 字以内）。</summary>
        [MaxLength(256)]
        public string Title { get; set; } = string.Empty;

        /// <summary>任务摘要（1024 字以内），任务列表预览用，与 ChatSession.Summary 对齐。</summary>
        [MaxLength(1024)]
        public string Summary { get; set; } = string.Empty;

        /// <summary>1=用户未填，需 LLM 兜底；0=用户已填或已生成完成。决策 6-A。</summary>
        public bool IsTitleAutoGenerated { get; set; }

        /// <summary>顶层模式 "discussion" / "execution"。</summary>
        [MaxLength(32)]
        public string Mode { get; set; } = string.Empty;

        /// <summary>子模式 "groupchat" / "magentic" / "parallelanalysis" / "handoffexecution"。</summary>
        [MaxLength(32)]
        public string SubMode { get; set; } = string.Empty;

        /// <summary>状态 "pending" / "running" / "paused" / "completed" / "failed" / "cancelled"。</summary>
        [MaxLength(32)]
        public string Status { get; set; } = string.Empty;

        /// <summary>任务启动时间（Unix ms）。</summary>
        public long StartedAt { get; set; }

        /// <summary>任务完成时间（Unix ms），未完成时为 null。</summary>
        public long? CompletedAt { get; set; }

        /// <summary>
        /// 最后活动时间戳（Unix ms），列表排序主键，与 ChatSession.LastActiveTimestamp 对齐。
        /// 启动 / 单步完成 / 任务结束 / 标题更新 时全部更新。
        /// </summary>
        public long LastActiveTimestamp { get; set; }

        /// <summary>Markdown 最终报告。</summary>
        public string? FinalReport { get; set; }

        /// <summary>追踪 ID，与 ChatSession 的 traceId 一致以便串联审计。</summary>
        [MaxLength(64)]
        public string TraceId { get; set; } = string.Empty;

        /// <summary>触发任务的来源："user" / "chat-suggested" / "duplicated" / "schedule"。</summary>
        [MaxLength(32)]
        public string CreatedBy { get; set; } = string.Empty;

        /// <summary>触发该任务的 Chat 会话 ID（如有）。</summary>
        [MaxLength(64)]
        public string? SourceSessionId { get; set; }

        /// <summary>决策 10-A：复制为新任务时记录原任务 ID（追踪用，不影响执行）。</summary>
        [MaxLength(64)]
        public string? SourceTaskId { get; set; }

        /// <summary>Magentic Manager / GroupChat Moderator 的智能体 ID。</summary>
        [MaxLength(64)]
        public string? ManagerAgentId { get; set; }

        /// <summary>Manager 智能体显示名称（冗余存储，便于审计）。</summary>
        [MaxLength(128)]
        public string? ManagerAgentName { get; set; }

        /// <summary>任务初始描述（用户输入）。</summary>
        public string InitialInput { get; set; } = string.Empty;

        /// <summary>JSON 数组，附件路径与描述。</summary>
        public string? InitialAttachmentsJson { get; set; }

        /// <summary>失败时的错误摘要。</summary>
        public string? ErrorMessage { get; set; }

        /// <summary>工作区标识（与 ChatSession.Categorize 同源），列表 WHERE 主条件。</summary>
        [MaxLength(64)]
        public string WorkspaceId { get; set; } = string.Empty;

        /// <summary>置顶（列表优先），与 ChatSession.IsPinned 对齐。决策 7-A。</summary>
        public bool IsPinned { get; set; }

        /// <summary>归档（默认列表不显示），与 ChatSession.IsArchived 对齐。决策 7-A。</summary>
        public bool IsArchived { get; set; }

        /// <summary>累计 token 用量（输入+输出），与 ChatSession.TotalTokenCount 对齐。</summary>
        public long TotalTokenCount { get; set; }

        /// <summary>阶段 5B+ 起：保存 WorkflowTaskOverrides（MaxRounds 等覆盖）。</summary>
        public string? OverridesJson { get; set; }

        /// <summary>
        /// 阶段 6 Phase 2：任务级工具黑名单（JSON 字符串数组，元素格式 "pluginId:toolName"）。
        /// 用户在 NewTaskDialog 上勾选"本次禁用高风险工具"时填充；
        /// <see cref="AI.AIAgentFactory.AssembleToolProviders"/> 在为 sub-agent 构建工具集时按此列表过滤掉对应函数。
        /// null 或空字符串表示不过滤（向后兼容，旧任务行为不变）。
        /// 详见 docs/未来版本策划/多智能体编排模式策划/04-实施阶段.md §阶段 6 #1 + 05-风险与规避.md §风险 7。
        /// </summary>
        public string? ToolBlacklistJson { get; set; }
    }
}
