<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Madorin.AI.Runtime.Tools.Abstractions\Madorin.AI.Runtime.Tools.Abstractions.csproj" />
    <ProjectReference Include="..\Madorin.AI.Runtime.Services\Madorin.AI.Runtime.Services.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
