using Microsoft.Data.Sqlite;

using System;
using System.Collections.Generic;

namespace Netor.Cortana.Entitys.Services
{
    /// <summary>
    /// Workflow 任务数据服务，提供对 OrchestrationTask 表的增删改查操作。
    /// 详见 docs/未来版本策划/多智能体编排模式策划/04-实施阶段.md §2B.2 / §2B.3。
    /// </summary>
    /// <remarks>
    /// 与 ChatHistoryPanel 的查询模式对齐：
    /// - ListByWorkspace：IsPinned DESC, LastActiveTimestamp DESC（决策 7-A）
    /// - QueryByStatuses：用于宿主重启孤儿清理（决策 9-A）
    /// - BuildTemplateFromSource：复制为新任务（决策 10-A，仅返回 dehydrated 字段，不直接写表）
    /// </remarks>
    public sealed class WorkflowTaskRepository(CortanaDbContext db)
    {
        private readonly CortanaDbContext _db = db ?? throw new ArgumentNullException(nameof(db));

        // ──── CRUD ────

        /// <summary>插入一条任务记录。</summary>
        public void Insert(OrchestrationTaskEntity entity)
        {
            ArgumentNullException.ThrowIfNull(entity);
            entity.CreatedTimestamp = DateTimeOffset.Now.ToUnixTimeMilliseconds();
            entity.UpdatedTimestamp = entity.CreatedTimestamp;

            _db.Execute("""
                INSERT INTO OrchestrationTask
                    (Id, CreatedTimestamp, UpdatedTimestamp, Title, Summary, IsTitleAutoGenerated,
                     Mode, SubMode, Status, StartedAt, CompletedAt, LastActiveTimestamp,
                     FinalReport, TraceId, CreatedBy, SourceSessionId, SourceTaskId,
                     ManagerAgentId, ManagerAgentName, InitialInput, InitialAttachmentsJson,
                     ErrorMessage, WorkspaceId, IsPinned, IsArchived, TotalTokenCount, OverridesJson,
                     ToolBlacklistJson)
                VALUES
                    (@Id, @CreatedTimestamp, @UpdatedTimestamp, @Title, @Summary, @IsTitleAutoGenerated,
                     @Mode, @SubMode, @Status, @StartedAt, @CompletedAt, @LastActiveTimestamp,
                     @FinalReport, @TraceId, @CreatedBy, @SourceSessionId, @SourceTaskId,
                     @ManagerAgentId, @ManagerAgentName, @InitialInput, @InitialAttachmentsJson,
                     @ErrorMessage, @WorkspaceId, @IsPinned, @IsArchived, @TotalTokenCount, @OverridesJson,
                     @ToolBlacklistJson)
                """,
                cmd => BindEntity(cmd, entity));
        }

        /// <summary>按主键查询任务，未找到时返回 null。</summary>
        public OrchestrationTaskEntity? GetById(string id)
        {
            if (string.IsNullOrWhiteSpace(id)) return null;
            return _db.QueryFirstOrDefault(
                "SELECT * FROM OrchestrationTask WHERE Id = @Id",
                ReadEntity,
                cmd => cmd.Parameters.AddWithValue("@Id", id));
        }

        /// <summary>按主键删除任务（CASCADE 级联删除 Participant / Step / Message）。</summary>
        public void Delete(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                throw new ArgumentException("Id cannot be null or empty.", nameof(id));

            _db.Execute("DELETE FROM OrchestrationTask WHERE Id = @Id",
                cmd => cmd.Parameters.AddWithValue("@Id", id));
        }

        // ──── 列表查询（决策 7-A：与 ChatHistoryPanel 对齐） ────

        /// <summary>
        /// 按工作区列表查询任务，置顶优先，最近活跃优先。
        /// </summary>
        /// <param name="workspaceId">工作区 ID。空字符串表示不过滤。</param>
        /// <param name="includeArchived">是否包含归档项；默认 false（与 Chat 列表一致）。</param>
        /// <param name="statuses">状态过滤（可空，传 null 表示不过滤）。</param>
        /// <param name="limit">每页数量。</param>
        /// <param name="offset">分页偏移。</param>
        /// <param name="keyword">
        /// 阶段 6 Phase 3 新增：标题搜索关键词（决策 6-3-A 子串 LIKE 匹配）。
        /// null 或空字符串表示不过滤；非空时按 LOWER(Title) LIKE LOWER('%keyword%') 匹配。
        /// 一期不引入 FTS5（推到阶段 7+），少量数据 LIKE 性能可接受。
        /// 详见 docs/未来版本策划/多智能体编排模式策划/04-实施阶段.md §阶段 6 #3。
        /// </param>
        /// <param name="subModes">
        /// P1 群聊真实化新增：子模式过滤（收尾决策 DT-9，2026-05-16 落地）。
        /// null 或空集合表示不过滤；非空时按 SubMode IN (...) 匹配。
        /// 「工作流」tab 传 ["magentic", "parallelanalysis"]；「群聊」tab 传 ["groupchat"]。
        /// 详见 Docs/未来版本策划/界面重设计/05-阶段总结.md §3.1 + §6.2。
        /// </param>
        public List<OrchestrationTaskEntity> ListByWorkspace(
            string workspaceId,
            bool includeArchived = false,
            IReadOnlyList<string>? statuses = null,
            int limit = 30,
            int offset = 0,
            string? keyword = null,
            IReadOnlyList<string>? subModes = null)
        {
            var sql = "SELECT * FROM OrchestrationTask WHERE 1=1";
            if (!string.IsNullOrEmpty(workspaceId)) sql += " AND WorkspaceId = @WorkspaceId";
            if (!includeArchived) sql += " AND IsArchived = 0";

            // 阶段 6 Phase 3：标题关键词过滤（子串 LIKE 匹配，大小写不敏感）
            var hasKeyword = !string.IsNullOrWhiteSpace(keyword);
            if (hasKeyword)
                sql += " AND LOWER(Title) LIKE LOWER(@Keyword)";

            // 状态过滤：参数化拼接（数量受调用方控制，无 SQL 注入风险）
            string[] statusParamNames = [];
            if (statuses is { Count: > 0 })
            {
                statusParamNames = new string[statuses.Count];
                for (var i = 0; i < statuses.Count; i++)
                    statusParamNames[i] = "@Status" + i;
                sql += $" AND Status IN ({string.Join(", ", statusParamNames)})";
            }

            // P1 群聊真实化：SubMode 过滤（参数化拼接，与状态过滤同款风格）
            string[] subModeParamNames = [];
            if (subModes is { Count: > 0 })
            {
                subModeParamNames = new string[subModes.Count];
                for (var i = 0; i < subModes.Count; i++)
                    subModeParamNames[i] = "@SubMode" + i;
                sql += $" AND SubMode IN ({string.Join(", ", subModeParamNames)})";
            }

            sql += " ORDER BY IsPinned DESC, LastActiveTimestamp DESC LIMIT @Limit OFFSET @Offset";

            return _db.Query(sql, ReadEntity, cmd =>
            {
                if (!string.IsNullOrEmpty(workspaceId))
                    cmd.Parameters.AddWithValue("@WorkspaceId", workspaceId);

                if (hasKeyword)
                    cmd.Parameters.AddWithValue("@Keyword", $"%{keyword!.Trim()}%");

                if (statuses is { Count: > 0 })
                    for (var i = 0; i < statuses.Count; i++)
                        cmd.Parameters.AddWithValue(statusParamNames[i], statuses[i]);

                // P1 群聊真实化：SubMode 参数绑定
                if (subModes is { Count: > 0 })
                    for (var i = 0; i < subModes.Count; i++)
                        cmd.Parameters.AddWithValue(subModeParamNames[i], subModes[i]);

                cmd.Parameters.AddWithValue("@Limit", limit);
                cmd.Parameters.AddWithValue("@Offset", offset);
            });
        }

        /// <summary>按状态列表查询所有任务（不分页）。用于宿主重启孤儿清理（决策 9-A）。</summary>
        public List<OrchestrationTaskEntity> QueryByStatuses(IReadOnlyList<string> statuses)
        {
            if (statuses is null || statuses.Count == 0) return [];

            var paramNames = new string[statuses.Count];
            for (var i = 0; i < statuses.Count; i++)
                paramNames[i] = "@Status" + i;

            var sql = $"SELECT * FROM OrchestrationTask WHERE Status IN ({string.Join(", ", paramNames)})";

            return _db.Query(sql, ReadEntity, cmd =>
            {
                for (var i = 0; i < statuses.Count; i++)
                    cmd.Parameters.AddWithValue(paramNames[i], statuses[i]);
            });
        }

        // ──── 列表元数据操作 ────

        /// <summary>设置置顶状态。</summary>
        public void SetPinned(string id, bool pinned)
        {
            if (string.IsNullOrWhiteSpace(id))
                throw new ArgumentException("Id cannot be null or empty.", nameof(id));

            var now = DateTimeOffset.Now.ToUnixTimeMilliseconds();
            _db.Execute(
                "UPDATE OrchestrationTask SET IsPinned = @Pinned, UpdatedTimestamp = @Now WHERE Id = @Id",
                cmd =>
                {
                    cmd.Parameters.AddWithValue("@Pinned", pinned ? 1 : 0);
                    cmd.Parameters.AddWithValue("@Now", now);
                    cmd.Parameters.AddWithValue("@Id", id);
                });
        }

        /// <summary>设置归档状态。</summary>
        public void SetArchived(string id, bool archived)
        {
            if (string.IsNullOrWhiteSpace(id))
                throw new ArgumentException("Id cannot be null or empty.", nameof(id));

            var now = DateTimeOffset.Now.ToUnixTimeMilliseconds();
            _db.Execute(
                "UPDATE OrchestrationTask SET IsArchived = @Archived, UpdatedTimestamp = @Now WHERE Id = @Id",
                cmd =>
                {
                    cmd.Parameters.AddWithValue("@Archived", archived ? 1 : 0);
                    cmd.Parameters.AddWithValue("@Now", now);
                    cmd.Parameters.AddWithValue("@Id", id);
                });
        }

        /// <summary>更新标题（用户重命名或 LLM 兜底生成）。</summary>
        public void UpdateTitle(string id, string title, bool isAutoGenerated)
        {
            if (string.IsNullOrWhiteSpace(id))
                throw new ArgumentException("Id cannot be null or empty.", nameof(id));

            var now = DateTimeOffset.Now.ToUnixTimeMilliseconds();
            _db.Execute("""
                UPDATE OrchestrationTask SET
                    Title = @Title,
                    IsTitleAutoGenerated = @IsAutoGenerated,
                    LastActiveTimestamp = @Now,
                    UpdatedTimestamp = @Now
                WHERE Id = @Id
                """,
                cmd =>
                {
                    cmd.Parameters.AddWithValue("@Title", title ?? string.Empty);
                    cmd.Parameters.AddWithValue("@IsAutoGenerated", isAutoGenerated ? 1 : 0);
                    cmd.Parameters.AddWithValue("@Now", now);
                    cmd.Parameters.AddWithValue("@Id", id);
                });
        }

        /// <summary>更新最后活跃时间戳（启动 / 单步完成 / 标题更新等场景）。</summary>
        public void TouchLastActive(string id, long timestamp)
        {
            if (string.IsNullOrWhiteSpace(id))
                throw new ArgumentException("Id cannot be null or empty.", nameof(id));

            _db.Execute(
                "UPDATE OrchestrationTask SET LastActiveTimestamp = @Ts, UpdatedTimestamp = @Ts WHERE Id = @Id",
                cmd =>
                {
                    cmd.Parameters.AddWithValue("@Ts", timestamp);
                    cmd.Parameters.AddWithValue("@Id", id);
                });
        }

        /// <summary>更新任务为已完成状态。</summary>
        public void UpdateCompleted(
            string id,
            string status,
            string? finalReport,
            string? errorMessage,
            long completedAt,
            long lastActiveTimestamp,
            long totalTokenCount = 0)
        {
            if (string.IsNullOrWhiteSpace(id))
                throw new ArgumentException("Id cannot be null or empty.", nameof(id));

            _db.Execute("""
                UPDATE OrchestrationTask SET
                    Status = @Status,
                    FinalReport = @FinalReport,
                    ErrorMessage = @ErrorMessage,
                    CompletedAt = @CompletedAt,
                    LastActiveTimestamp = @LastActiveTimestamp,
                    TotalTokenCount = @TotalTokenCount,
                    UpdatedTimestamp = @LastActiveTimestamp
                WHERE Id = @Id
                """,
                cmd =>
                {
                    cmd.Parameters.AddWithValue("@Status", status);
                    cmd.Parameters.AddWithValue("@FinalReport", (object?)finalReport ?? DBNull.Value);
                    cmd.Parameters.AddWithValue("@ErrorMessage", (object?)errorMessage ?? DBNull.Value);
                    cmd.Parameters.AddWithValue("@CompletedAt", completedAt);
                    cmd.Parameters.AddWithValue("@LastActiveTimestamp", lastActiveTimestamp);
                    cmd.Parameters.AddWithValue("@TotalTokenCount", totalTokenCount);
                    cmd.Parameters.AddWithValue("@Id", id);
                });
        }

        /// <summary>
        /// 更新任务为 paused 状态（HITL 暂停，阶段 5B 新增）。
        /// 仅修改 Status + LastActiveTimestamp + UpdatedTimestamp。
        /// HITL 上下文（RequestId / RequestPayloadJson）存在运行时内存中，
        /// 不持久化到表（避免引入 schema migration；UI 通过实时 event 获取详情）。
        /// </summary>
        public void UpdatePaused(string id, long pausedAt)
        {
            if (string.IsNullOrWhiteSpace(id))
                throw new ArgumentException("Id cannot be null or empty.", nameof(id));

            _db.Execute("""
                UPDATE OrchestrationTask SET
                    Status = @Status,
                    LastActiveTimestamp = @PausedAt,
                    UpdatedTimestamp = @PausedAt
                WHERE Id = @Id
                """,
                cmd =>
                {
                    cmd.Parameters.AddWithValue("@Status", "paused");
                    cmd.Parameters.AddWithValue("@PausedAt", pausedAt);
                    cmd.Parameters.AddWithValue("@Id", id);
                });
        }

        /// <summary>
        /// 更新任务为 running 状态（HITL 恢复，阶段 5B 新增）。
        /// 仅修改 Status + LastActiveTimestamp + UpdatedTimestamp。
        /// </summary>
        public void UpdateRunning(string id, long resumedAt)
        {
            if (string.IsNullOrWhiteSpace(id))
                throw new ArgumentException("Id cannot be null or empty.", nameof(id));

            _db.Execute("""
                UPDATE OrchestrationTask SET
                    Status = @Status,
                    LastActiveTimestamp = @ResumedAt,
                    UpdatedTimestamp = @ResumedAt
                WHERE Id = @Id
                """,
                cmd =>
                {
                    cmd.Parameters.AddWithValue("@Status", "running");
                    cmd.Parameters.AddWithValue("@ResumedAt", resumedAt);
                    cmd.Parameters.AddWithValue("@Id", id);
                });
        }

        // ──── ReadEntity / BindEntity ────

        private static OrchestrationTaskEntity ReadEntity(SqliteDataReader r) => new()
        {
            Id = r.GetString(r.GetOrdinal("Id")),
            CreatedTimestamp = r.GetInt64(r.GetOrdinal("CreatedTimestamp")),
            UpdatedTimestamp = r.GetInt64(r.GetOrdinal("UpdatedTimestamp")),
            Title = r.GetString(r.GetOrdinal("Title")),
            Summary = r.GetString(r.GetOrdinal("Summary")),
            IsTitleAutoGenerated = r.GetInt32(r.GetOrdinal("IsTitleAutoGenerated")) != 0,
            Mode = r.GetString(r.GetOrdinal("Mode")),
            SubMode = r.GetString(r.GetOrdinal("SubMode")),
            Status = r.GetString(r.GetOrdinal("Status")),
            StartedAt = r.GetInt64(r.GetOrdinal("StartedAt")),
            CompletedAt = r.IsDBNull(r.GetOrdinal("CompletedAt")) ? null : r.GetInt64(r.GetOrdinal("CompletedAt")),
            LastActiveTimestamp = r.GetInt64(r.GetOrdinal("LastActiveTimestamp")),
            FinalReport = r.IsDBNull(r.GetOrdinal("FinalReport")) ? null : r.GetString(r.GetOrdinal("FinalReport")),
            TraceId = r.GetString(r.GetOrdinal("TraceId")),
            CreatedBy = r.GetString(r.GetOrdinal("CreatedBy")),
            SourceSessionId = r.IsDBNull(r.GetOrdinal("SourceSessionId")) ? null : r.GetString(r.GetOrdinal("SourceSessionId")),
            SourceTaskId = r.IsDBNull(r.GetOrdinal("SourceTaskId")) ? null : r.GetString(r.GetOrdinal("SourceTaskId")),
            ManagerAgentId = r.IsDBNull(r.GetOrdinal("ManagerAgentId")) ? null : r.GetString(r.GetOrdinal("ManagerAgentId")),
            ManagerAgentName = r.IsDBNull(r.GetOrdinal("ManagerAgentName")) ? null : r.GetString(r.GetOrdinal("ManagerAgentName")),
            InitialInput = r.GetString(r.GetOrdinal("InitialInput")),
            InitialAttachmentsJson = r.IsDBNull(r.GetOrdinal("InitialAttachmentsJson")) ? null : r.GetString(r.GetOrdinal("InitialAttachmentsJson")),
            ErrorMessage = r.IsDBNull(r.GetOrdinal("ErrorMessage")) ? null : r.GetString(r.GetOrdinal("ErrorMessage")),
            WorkspaceId = r.GetString(r.GetOrdinal("WorkspaceId")),
            IsPinned = r.GetInt32(r.GetOrdinal("IsPinned")) != 0,
            IsArchived = r.GetInt32(r.GetOrdinal("IsArchived")) != 0,
            TotalTokenCount = r.GetInt64(r.GetOrdinal("TotalTokenCount")),
            OverridesJson = r.IsDBNull(r.GetOrdinal("OverridesJson")) ? null : r.GetString(r.GetOrdinal("OverridesJson")),
            // 阶段 6 Phase 2：任务级工具黑名单（JSON 数组 "pluginId:toolName"），null 表示不过滤
            ToolBlacklistJson = r.IsDBNull(r.GetOrdinal("ToolBlacklistJson")) ? null : r.GetString(r.GetOrdinal("ToolBlacklistJson")),
        };

        private static void BindEntity(SqliteCommand cmd, OrchestrationTaskEntity e)
        {
            cmd.Parameters.AddWithValue("@Id", e.Id);
            cmd.Parameters.AddWithValue("@CreatedTimestamp", e.CreatedTimestamp);
            cmd.Parameters.AddWithValue("@UpdatedTimestamp", e.UpdatedTimestamp);
            cmd.Parameters.AddWithValue("@Title", e.Title ?? string.Empty);
            cmd.Parameters.AddWithValue("@Summary", e.Summary ?? string.Empty);
            cmd.Parameters.AddWithValue("@IsTitleAutoGenerated", e.IsTitleAutoGenerated ? 1 : 0);
            cmd.Parameters.AddWithValue("@Mode", e.Mode ?? string.Empty);
            cmd.Parameters.AddWithValue("@SubMode", e.SubMode ?? string.Empty);
            cmd.Parameters.AddWithValue("@Status", e.Status ?? string.Empty);
            cmd.Parameters.AddWithValue("@StartedAt", e.StartedAt);
            cmd.Parameters.AddWithValue("@CompletedAt", (object?)e.CompletedAt ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@LastActiveTimestamp", e.LastActiveTimestamp);
            cmd.Parameters.AddWithValue("@FinalReport", (object?)e.FinalReport ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@TraceId", e.TraceId ?? string.Empty);
            cmd.Parameters.AddWithValue("@CreatedBy", e.CreatedBy ?? string.Empty);
            cmd.Parameters.AddWithValue("@SourceSessionId", (object?)e.SourceSessionId ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@SourceTaskId", (object?)e.SourceTaskId ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@ManagerAgentId", (object?)e.ManagerAgentId ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@ManagerAgentName", (object?)e.ManagerAgentName ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@InitialInput", e.InitialInput ?? string.Empty);
            cmd.Parameters.AddWithValue("@InitialAttachmentsJson", (object?)e.InitialAttachmentsJson ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@ErrorMessage", (object?)e.ErrorMessage ?? DBNull.Value);
            cmd.Parameters.AddWithValue("@WorkspaceId", e.WorkspaceId ?? string.Empty);
            cmd.Parameters.AddWithValue("@IsPinned", e.IsPinned ? 1 : 0);
            cmd.Parameters.AddWithValue("@IsArchived", e.IsArchived ? 1 : 0);
            cmd.Parameters.AddWithValue("@TotalTokenCount", e.TotalTokenCount);
            cmd.Parameters.AddWithValue("@OverridesJson", (object?)e.OverridesJson ?? DBNull.Value);
            // 阶段 6 Phase 2：任务级工具黑名单
            cmd.Parameters.AddWithValue("@ToolBlacklistJson", (object?)e.ToolBlacklistJson ?? DBNull.Value);
        }
    }
}
