using Netor.Cortana.Plugin.Native.Generator.Analysis;

using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Netor.Cortana.Plugin.Native.Generator.Emitters;

/// <summary>
/// 生成 Startup.g.cs：路由字典 + 桥接方法 + 5 个导出函数 + ServiceProvider 管理。
/// </summary>
internal static class StartupEmitter
{
    /// <summary>
    /// 生成完整的 Startup.g.cs 源代码。
    /// </summary>
    public static string Emit(PluginClassInfo plugin, List<ToolClassInfo> toolClasses)
    {
        var sb = new StringBuilder();

        EmitHeader(sb, plugin);
        EmitServiceProviderField(sb);
        EmitRouteDict(sb, toolClasses);
        EmitGetInfo(sb, plugin, toolClasses);
        EmitInit(sb, plugin, toolClasses);
        EmitInvoke(sb);
        EmitBridgeMethods(sb, toolClasses);
        EmitFree(sb);
        EmitDestroy(sb);

        // 关闭类
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// 生成文件头：auto-generated 注释 + using + partial class 开头。
    /// </summary>
    private static void EmitHeader(StringBuilder sb, PluginClassInfo plugin)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// 由 Netor.Cortana.Plugin.Native.Generator 自动生成");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine("using Netor.Cortana.Plugin.Native;");
        sb.AppendLine();

        if (plugin.Namespace != null)
        {
            sb.AppendLine($"namespace {plugin.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public static partial class {plugin.ClassName}");
        sb.AppendLine("{");
    }

    /// <summary>
    /// 生成静态 ServiceProvider 字段和 FormatError/EscapeJsonValue 辅助方法。
    /// </summary>
    private static void EmitServiceProviderField(StringBuilder sb)
    {
        sb.AppendLine("    // 官方 DI 容器");
        sb.AppendLine("    private static global::Microsoft.Extensions.DependencyInjection.ServiceProvider? s_serviceProvider;");
        sb.AppendLine();

        // FormatError：手动拼接 JSON，避免跨 source-gen 依赖 JsonSerializerContext
        sb.AppendLine("    private static string FormatError(string error, string tool)");
        sb.AppendLine("    {");
        // 生成: return "{\"error\":\"" + EscapeJsonValue(error) + "\",\"tool\":\"" + EscapeJsonValue(tool) + "\"}";
        var q = "\\\""; // 在生成的代码中表示 \"
        sb.AppendLine($"        return \"{{{q}error{q}:{q}\" + EscapeJsonValue(error) + \"{q},{q}tool{q}:{q}\" + EscapeJsonValue(tool) + \"{q}}}\";");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string EscapeJsonValue(string s)");
        sb.AppendLine("    {");
        // 生成: return s.Replace("\", "\\").Replace("\"", "\\\"");
        var bs = "\\\\";   // 生成的代码中的 \\
        var bsbs = bs + bs; // 生成的代码中的 \\\\
        sb.AppendLine($"        return s.Replace(\"{bs}\", \"{bsbs}\").Replace(\"{q}\", \"{bs}{q}\");");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成路由字典：工具名 → Func&lt;IServiceProvider, string, string&gt;。
    /// </summary>
    private static void EmitRouteDict(StringBuilder sb, List<ToolClassInfo> toolClasses)
    {
        sb.AppendLine("    // ──── 路由字典（Generator 从 [Tool] 标记扫描生成） ────");
        sb.AppendLine("    private static readonly global::System.Collections.Generic.Dictionary<string, global::System.Func<global::System.IServiceProvider, string, string>> s_toolRoutes = new()");
        sb.AppendLine("    {");

        foreach (var toolClass in toolClasses)
        {
            foreach (var method in toolClass.Methods)
            {
                var bridgeName = $"Invoke_{toolClass.ClassName}_{method.MethodName}";

                if (method.Parameters.Count > 0)
                {
                    sb.AppendLine($"        [\"{method.FullToolName}\"] = {bridgeName},");
                }
                else
                {
                    sb.AppendLine($"        [\"{method.FullToolName}\"] = (sp, _) => {bridgeName}(sp),");
                }
            }
        }

        sb.AppendLine("    };");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成 cortana_plugin_get_info 导出函数。
    /// </summary>
    private static void EmitGetInfo(StringBuilder sb, PluginClassInfo plugin, List<ToolClassInfo> toolClasses)
    {
        var infoJson = InfoJsonEmitter.EmitInfoJson(plugin, toolClasses);

        sb.AppendLine("    // ──────── cortana_plugin_get_info ────────");
        sb.AppendLine();
        sb.AppendLine("    [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = \"cortana_plugin_get_info\")]");
        sb.AppendLine("    public static global::System.IntPtr GetInfo()");
        sb.AppendLine("    {");
        sb.AppendLine("        const string json = @\"");
        sb.Append(infoJson.Replace("\"", "\"\""));
        sb.AppendLine("\";");
        sb.AppendLine("        return global::System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(json);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成 cortana_plugin_init 导出函数。
    /// 自动注册 [Tool] 类 → 内置服务 → 调用 Configure → BuildServiceProvider → 启动 IHostedService。
    /// </summary>
    private static void EmitInit(StringBuilder sb, PluginClassInfo plugin, List<ToolClassInfo> toolClasses)
    {
        sb.AppendLine("    // ──────── cortana_plugin_init ────────");
        sb.AppendLine();
        sb.AppendLine("    [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = \"cortana_plugin_init\")]");
        sb.AppendLine("    public static int Init(global::System.IntPtr configJsonPtr)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            var configJson = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(configJsonPtr) ?? \"{}\";");
        sb.AppendLine();
        sb.AppendLine("            // 1. 创建 ServiceCollection 并注册内置服务");
        sb.AppendLine("            var services = new global::Microsoft.Extensions.DependencyInjection.ServiceCollection();");
        sb.AppendLine("            var settings = PluginSettings.FromJson(configJson);");
        sb.AppendLine("            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton(services, settings);");
        sb.AppendLine();
        sb.AppendLine("            // 2. Generator 自动注册所有 [Tool] 标记的类");

        foreach (var toolClass in toolClasses)
        {
            var fullName = toolClass.ClassSymbol.ToDisplayString();
            sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::{fullName}>(services);");
        }

        sb.AppendLine();
        sb.AppendLine("            // 3. 调用开发者的 Configure 方法");
        sb.AppendLine($"            Configure(services);");
        sb.AppendLine();
        sb.AppendLine("            // 4. 构建 ServiceProvider");
        sb.AppendLine("            s_serviceProvider = global::Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(services);");
        sb.AppendLine();
        sb.AppendLine("            // 5. 启动所有 IHostedService");
        sb.AppendLine("            var hostedServices = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Hosting.IHostedService>(s_serviceProvider);");
        sb.AppendLine("            foreach (var svc in hostedServices)");
        sb.AppendLine("            {");
        sb.AppendLine("                _ = svc.StartAsync(global::System.Threading.CancellationToken.None);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return 1;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch");
        sb.AppendLine("        {");
        sb.AppendLine("            return 0;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成 cortana_plugin_invoke 导出函数（Dictionary 路由）。
    /// </summary>
    private static void EmitInvoke(StringBuilder sb)
    {
        sb.AppendLine("    // ──────── cortana_plugin_invoke ────────");
        sb.AppendLine();
        sb.AppendLine("    [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = \"cortana_plugin_invoke\")]");
        sb.AppendLine("    public static global::System.IntPtr Invoke(global::System.IntPtr toolNamePtr, global::System.IntPtr argsJsonPtr)");
        sb.AppendLine("    {");
        sb.AppendLine("        var toolName = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(toolNamePtr) ?? \"\";");
        sb.AppendLine("        var argsJson = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(argsJsonPtr) ?? \"{}\";");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            string result;");
        sb.AppendLine("            if (s_toolRoutes.TryGetValue(toolName, out var handler))");
        sb.AppendLine("            {");
        sb.AppendLine("                result = handler(s_serviceProvider!, argsJson);");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine("                result = FormatError($\"未知工具: {toolName}\", toolName);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return global::System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(result);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (global::System.Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            var error = FormatError(ex.Message, toolName);");
        sb.AppendLine("            return global::System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(error);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成所有桥接方法：参数解析 + sp.GetRequiredService + 业务调用 + 错误处理。
    /// 方法签名：private static string Invoke_{ClassName}_{MethodName}(IServiceProvider sp, string argsJson)
    /// 无参方法：private static string Invoke_{ClassName}_{MethodName}(IServiceProvider sp)
    /// </summary>
    private static void EmitBridgeMethods(StringBuilder sb, List<ToolClassInfo> toolClasses)
    {
        sb.AppendLine("    // ──────── 桥接方法（Generator 生成，参数解析 + 业务调用） ────────");
        sb.AppendLine();

        foreach (var toolClass in toolClasses)
        {
            foreach (var method in toolClass.Methods)
            {
                EmitSingleBridgeMethod(sb, toolClass, method);
                sb.AppendLine();
            }
        }
    }

    /// <summary>
    /// 生成单个桥接方法。
    /// </summary>
    private static void EmitSingleBridgeMethod(StringBuilder sb, ToolClassInfo toolClass, ToolMethodInfo method)
    {
        var bridgeName = $"Invoke_{toolClass.ClassName}_{method.MethodName}";
        var fullClassName = toolClass.ClassSymbol.ToDisplayString();

        if (method.Parameters.Count > 0)
        {
            sb.AppendLine($"    private static string {bridgeName}(global::System.IServiceProvider sp, string argsJson)");
        }
        else
        {
            sb.AppendLine($"    private static string {bridgeName}(global::System.IServiceProvider sp)");
        }

        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        // 参数解析
        if (method.Parameters.Count > 0)
        {
            sb.AppendLine("            using var doc = global::System.Text.Json.JsonDocument.Parse(argsJson);");

            foreach (var param in method.Parameters)
            {
                var parseExpr = TypeMapper.GetJsonParseExpression(
                    param.TypeSymbol,
                    $"doc.RootElement.GetProperty(\"{param.JsonName}\")");

                sb.AppendLine($"            var {param.CodeParamName} = {parseExpr};");
            }
        }

        // 获取服务实例
        sb.AppendLine($"            var tool = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::{fullClassName}>(sp);");

        // 方法调用
        var callArgs = string.Join(", ", method.Parameters.Select(p => p.CodeParamName));
        var callExpr = $"tool.{method.MethodName}({callArgs})";

        if (method.IsAsync)
        {
            if (method.IsValueTask)
                callExpr = $"{callExpr}.AsTask().GetAwaiter().GetResult()";
            else
                callExpr = $"{callExpr}.GetAwaiter().GetResult()";

            if (method.AsyncInnerType == null)
            {
                // Task (void)
                sb.AppendLine($"            {callExpr};");
                sb.AppendLine("            return \"ok\";");
            }
            else
            {
                // Task<T>
                sb.AppendLine($"            var result = {callExpr};");
                var convertExpr = TypeMapper.GetReturnConvertExpression(method.AsyncInnerType, "result");
                sb.AppendLine($"            return {convertExpr};");
            }
        }
        else
        {
            var effectiveType = method.ReturnType;
            if (TypeMapper.IsVoid(effectiveType))
            {
                sb.AppendLine($"            {callExpr};");
                sb.AppendLine("            return \"ok\";");
            }
            else
            {
                sb.AppendLine($"            var result = {callExpr};");
                var convertExpr = TypeMapper.GetReturnConvertExpression(effectiveType, "result");
                sb.AppendLine($"            return {convertExpr};");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine("        catch (global::System.Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return FormatError(ex.Message, \"{method.FullToolName}\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// 生成 cortana_plugin_free 导出函数。
    /// </summary>
    private static void EmitFree(StringBuilder sb)
    {
        sb.AppendLine("    // ──────── cortana_plugin_free ────────");
        sb.AppendLine();
        sb.AppendLine("    [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = \"cortana_plugin_free\")]");
        sb.AppendLine("    public static void Free(global::System.IntPtr ptr)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (ptr != global::System.IntPtr.Zero)");
        sb.AppendLine("            global::System.Runtime.InteropServices.Marshal.FreeCoTaskMem(ptr);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// 生成 cortana_plugin_destroy 导出函数：停止 IHostedService → Dispose ServiceProvider。
    /// </summary>
    private static void EmitDestroy(StringBuilder sb)
    {
        sb.AppendLine("    // ──────── cortana_plugin_destroy ────────");
        sb.AppendLine();
        sb.AppendLine("    [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = \"cortana_plugin_destroy\")]");
        sb.AppendLine("    public static void Destroy()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (s_serviceProvider is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 1. 停止所有 IHostedService");
        sb.AppendLine("            var hostedServices = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Microsoft.Extensions.Hosting.IHostedService>(s_serviceProvider);");
        sb.AppendLine("            foreach (var svc in hostedServices)");
        sb.AppendLine("            {");
        sb.AppendLine("                try { svc.StopAsync(global::System.Threading.CancellationToken.None).GetAwaiter().GetResult(); } catch { }");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // 2. Dispose ServiceProvider");
        sb.AppendLine("            s_serviceProvider.Dispose();");
        sb.AppendLine("            s_serviceProvider = null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
