// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Netor.Cortana.Platform.Entitys.Data;

#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    partial class PlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Accounts.Account", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<byte>("AccountType")
                        .HasColumnType("INTEGER")
                        .HasComment("账户类型");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(126)
                        .HasColumnType("TEXT")
                        .HasComment("电子邮箱");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER")
                        .HasComment("邮箱验证");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("头像128");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("TEXT")
                        .HasComment("登录时间");

                    b.Property<string>("LoginIP")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("登录IP");

                    b.Property<string>("LoginPassword")
                        .IsRequired()
                        .HasMaxLength(126)
                        .HasColumnType("TEXT")
                        .HasComment("登录密码");

                    b.Property<int>("LoginTimes")
                        .HasColumnType("INTEGER")
                        .HasComment("登录次数");

                    b.Property<string>("LoginUserName")
                        .IsRequired()
                        .HasMaxLength(126)
                        .HasColumnType("TEXT")
                        .HasComment("登录账号");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasComment("用户昵称");

                    b.Property<long>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1778476340211L)
                        .HasComment("会员编号");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasComment("手机号码");

                    b.Property<bool>("PhoneConfirmed")
                        .HasColumnType("INTEGER")
                        .HasComment("手机验证");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("真实名称");

                    b.Property<string>("Refer")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasComment("推荐人ID");

                    b.Property<string>("RegestorIP")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("注册IP");

                    b.Property<string>("SafePassword")
                        .IsRequired()
                        .HasMaxLength(126)
                        .HasColumnType("TEXT")
                        .HasComment("安全密码");

                    b.Property<byte>("Sex")
                        .HasColumnType("INTEGER")
                        .HasComment("性别");

                    b.Property<bool>("SingleLoginEnabled")
                        .HasColumnType("INTEGER")
                        .HasComment("单线登录");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER")
                        .HasComment("会员状态");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("Email");

                    b.HasIndex("No")
                        .IsUnique();

                    b.HasIndex("Phone");

                    b.ToTable("Accounts", t =>
                        {
                            t.HasComment("平台个人用户账户");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Accounts.AccountProperty", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("AccountID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasComment("描述");

                    b.Property<string>("Group")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("分组设置");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("属性键");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER")
                        .HasComment("类型");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasComment("属性值");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("AccountPropertys", t =>
                        {
                            t.HasComment("平台个人用户扩展属性");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Accounts.AccountRole", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasComment("详细介绍");

                    b.Property<bool>("Enabel")
                        .HasColumnType("INTEGER")
                        .HasComment("启用状态");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasComment("角色名称");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasComment("排序");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER")
                        .HasComment("角色权限(越大权利越大)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.ToTable("AccountRole", t =>
                        {
                            t.HasComment("平台个人用户角色");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Accounts.AccountRolePair", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("AccountID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("RoleID")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("RoleID");

                    b.ToTable("AccountRolePairs", t =>
                        {
                            t.HasComment("平台个人用户角色关联");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Accounts.AccountWallet", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<decimal>("Money")
                        .HasPrecision(18, 5)
                        .HasColumnType("TEXT")
                        .HasComment("金额");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasComment("名称");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER")
                        .HasComment("状态");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER")
                        .HasComment("钱包类型");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("AccountWallets", t =>
                        {
                            t.HasComment("平台个人用户钱包");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Assets.Asset", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasComment("分类ID");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasComment("封面地址");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("CurrentVersionId")
                        .HasColumnType("TEXT")
                        .HasComment("当前版本ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("详细描述");

                    b.Property<string>("DeveloperName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("开发者");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("INTEGER")
                        .HasComment("下载次数");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasComment("图标地址");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER")
                        .HasComment("是否推荐");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("名称");

                    b.Property<string>("OwnerAccountId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("归属账号ID");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("TEXT")
                        .HasComment("发布时间");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasComment("简短描述");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasComment("标识");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasComment("状态");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasComment("标签");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasComment("类型");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerAccountId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Type", "Status");

                    b.ToTable("Assets", t =>
                        {
                            t.HasComment("平台资源");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Assets.AssetVersion", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasComment("文件路径");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("清单JSON");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("包哈希");

                    b.Property<long>("PackageSize")
                        .HasColumnType("INTEGER")
                        .HasComment("包大小");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("发布说明");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("版本号");

                    b.HasKey("ID");

                    b.HasIndex("AssetId", "VersionName")
                        .IsUnique();

                    b.ToTable("AssetVersions", t =>
                        {
                            t.HasComment("平台资源版本");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Assets.Category", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasComment("描述");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER")
                        .HasComment("是否显示");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasComment("名称");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("标识");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasComment("排序");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", t =>
                        {
                            t.HasComment("平台资源分类");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Assets.PricingPlan", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasComment("货币");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER")
                        .HasComment("有效天数");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasComment("是否启用");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasComment("名称");

                    b.Property<int>("PlanType")
                        .HasColumnType("INTEGER")
                        .HasComment("方案类型");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasComment("价格");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("AssetId", "PlanType");

                    b.ToTable("PricingPlans", t =>
                        {
                            t.HasComment("平台资源定价方案");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Downloads.DownloadRecord", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetVersionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("AccountId");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetVersionId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("DownloadRecords", t =>
                        {
                            t.HasComment("平台下载记录");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Managers.Manager", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<byte>("AccountType")
                        .HasColumnType("INTEGER")
                        .HasComment("账户类型");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(126)
                        .HasColumnType("TEXT")
                        .HasComment("电子邮箱");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER")
                        .HasComment("邮箱验证");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("头像128");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("TEXT")
                        .HasComment("登录时间");

                    b.Property<string>("LoginIP")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("登录IP");

                    b.Property<string>("LoginPassword")
                        .IsRequired()
                        .HasMaxLength(126)
                        .HasColumnType("TEXT")
                        .HasComment("登录密码");

                    b.Property<int>("LoginTimes")
                        .HasColumnType("INTEGER")
                        .HasComment("登录次数");

                    b.Property<string>("LoginUserName")
                        .IsRequired()
                        .HasMaxLength(126)
                        .HasColumnType("TEXT")
                        .HasComment("登录账号");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasComment("用户昵称");

                    b.Property<long>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1778476340214L)
                        .HasComment("会员编号");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasComment("手机号码");

                    b.Property<bool>("PhoneConfirmed")
                        .HasColumnType("INTEGER")
                        .HasComment("手机验证");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasComment("真实名称");

                    b.Property<string>("Refer")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasComment("推荐人ID");

                    b.Property<string>("RegestorIP")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("注册IP");

                    b.Property<string>("RoleID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafePassword")
                        .IsRequired()
                        .HasMaxLength(126)
                        .HasColumnType("TEXT")
                        .HasComment("安全密码");

                    b.Property<byte>("Sex")
                        .HasColumnType("INTEGER")
                        .HasComment("性别");

                    b.Property<bool>("SingleLoginEnabled")
                        .HasColumnType("INTEGER")
                        .HasComment("单线登录");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER")
                        .HasComment("会员状态");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("Email");

                    b.HasIndex("No")
                        .IsUnique();

                    b.HasIndex("Phone");

                    b.HasIndex("RoleID");

                    b.ToTable("Managers", t =>
                        {
                            t.HasComment("平台管理员账户");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Managers.ManagerProperty", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("AccountID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasComment("描述");

                    b.Property<string>("Group")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("分组设置");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("属性键");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER")
                        .HasComment("类型");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasComment("属性值");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("ManagerProperty", t =>
                        {
                            t.HasComment("平台管理员扩展属性");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Managers.ManagerRole", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasComment("详细介绍");

                    b.Property<bool>("Enabel")
                        .HasColumnType("INTEGER")
                        .HasComment("启用状态");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasComment("角色名称");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER")
                        .HasComment("角色权限(越大权利越大)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.ToTable("ManagerRoles", t =>
                        {
                            t.HasComment("平台管理员角色");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Orders.Order", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .HasColumnType("TEXT")
                        .HasComment("资产ID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("详细");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<decimal>("Money")
                        .HasPrecision(18, 5)
                        .HasColumnType("TEXT")
                        .HasComment("金额");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("交易单号");

                    b.Property<int>("Numbers")
                        .HasColumnType("INTEGER")
                        .HasComment("交易数量");

                    b.Property<byte>("PayMethod")
                        .HasColumnType("INTEGER")
                        .HasComment("支付方式");

                    b.Property<byte>("PayStatus")
                        .HasColumnType("INTEGER")
                        .HasComment("支付状态");

                    b.Property<DateTime?>("PayTime")
                        .HasColumnType("TEXT")
                        .HasComment("支付时间");

                    b.Property<string>("PricingPlanId")
                        .HasColumnType("TEXT")
                        .HasComment("定价方案ID");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER")
                        .HasComment("订单状态");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("交易名称");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("No");

                    b.ToTable("Orders", t =>
                        {
                            t.HasComment("平台销售单");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Orders.Transaction", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("AccountID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2096)
                        .HasColumnType("TEXT")
                        .HasComment("交易内容(2096)");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<decimal>("Money")
                        .HasPrecision(18, 5)
                        .HasColumnType("TEXT")
                        .HasComment("金额");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("交易单号");

                    b.Property<int>("Numbers")
                        .HasColumnType("INTEGER")
                        .HasComment("交易数量");

                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT")
                        .HasComment("关联销售单ID");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("订单编号");

                    b.Property<byte>("PayMethod")
                        .HasColumnType("INTEGER")
                        .HasComment("支付方式");

                    b.Property<byte>("PayStatus")
                        .HasColumnType("INTEGER")
                        .HasComment("支付状态");

                    b.Property<DateTime?>("PayTime")
                        .HasColumnType("TEXT")
                        .HasComment("支付时间");

                    b.Property<decimal>("RealMoney")
                        .HasPrecision(18, 5)
                        .HasColumnType("TEXT")
                        .HasComment("实际金额");

                    b.Property<string>("ThirdNo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("三方单号");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("交易名称");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER")
                        .HasComment("记录类型");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("No", "OrderNo", "ThirdNo", "Type");

                    b.ToTable("Transactions", t =>
                        {
                            t.HasComment("平台交易记录");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Subscriptions.Subscription", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CanceledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PricingPlanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("AssetId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PricingPlanId");

                    b.HasIndex("AccountId", "Status");

                    b.HasIndex("AccountId", "AssetId", "Status");

                    b.ToTable("Subscriptions", t =>
                        {
                            t.HasComment("平台订阅记录");
                        });
                });

            modelBuilder.Entity("Netor.Database.Abstractions.AccountLayer", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountNo")
                        .HasColumnType("INTEGER")
                        .HasComment("当前用户编号");

                    b.Property<long>("Index")
                        .HasColumnType("INTEGER")
                        .HasComment("当前层数");

                    b.Property<long>("ParentNo")
                        .HasColumnType("INTEGER")
                        .HasComment("父级用户编号");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间戳");

                    b.HasKey("ID");

                    b.HasIndex("AccountNo")
                        .IsUnique();

                    b.HasIndex("Index", "AccountNo", "ParentNo");

                    b.ToTable("AccountLayers", t =>
                        {
                            t.HasComment("用户层级关系");
                        });
                });

            modelBuilder.Entity("Netor.Database.Abstractions.SystemSetting", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("主键");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("创建者");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("说明");

                    b.Property<string>("Group")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("分组设置");

                    b.Property<bool>("IsProtection")
                        .HasColumnType("INTEGER")
                        .HasComment("是否保护");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasComment("标识");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasComment("名称");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER")
                        .HasComment("创建时间(秒)");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER")
                        .HasComment("类型");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasComment("值");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasComment("并发版本");

                    b.HasKey("ID");

                    b.HasIndex("Key");

                    b.ToTable("SystemSettings", t =>
                        {
                            t.HasComment("系统设置");
                        });
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Accounts.AccountProperty", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Accounts.Account", "Account")
                        .WithMany("Properties")
                        .HasForeignKey("AccountID");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Accounts.AccountRolePair", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Accounts.Account", "Account")
                        .WithMany("RolePairs")
                        .HasForeignKey("AccountID");

                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Accounts.AccountRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Accounts.AccountWallet", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Accounts.Account", "Account")
                        .WithMany("Wallets")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Assets.Asset", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Assets.Category", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Accounts.Account", "OwnerAccount")
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Assets.AssetVersion", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Assets.Asset", "Asset")
                        .WithMany("Versions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Assets.PricingPlan", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Assets.Asset", "Asset")
                        .WithMany("PricingPlans")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Downloads.DownloadRecord", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Assets.AssetVersion", "AssetVersion")
                        .WithMany()
                        .HasForeignKey("AssetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Subscriptions.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Asset");

                    b.Navigation("AssetVersion");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Managers.Manager", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Managers.ManagerRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Managers.ManagerProperty", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Managers.Manager", "Account")
                        .WithMany("Properties")
                        .HasForeignKey("AccountID");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Orders.Order", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Orders.Transaction", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Subscriptions.Subscription", b =>
                {
                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Assets.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Netor.Cortana.Platform.Entitys.Tables.Assets.PricingPlan", "PricingPlan")
                        .WithMany()
                        .HasForeignKey("PricingPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Asset");

                    b.Navigation("Order");

                    b.Navigation("PricingPlan");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Accounts.Account", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("RolePairs");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Assets.Asset", b =>
                {
                    b.Navigation("PricingPlans");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Assets.Category", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Netor.Cortana.Platform.Entitys.Tables.Managers.Manager", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
