<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Madorin.AI.Runtime.Orchestration.Abstractions\Madorin.AI.Runtime.Orchestration.Abstractions.csproj" />
    <ProjectReference Include="..\Madorin.AI.Runtime.Persistence.Files\Madorin.AI.Runtime.Persistence.Files.csproj" />
    <ProjectReference Include="..\Madorin.AI.Runtime.Persistence.Sqlite\Madorin.AI.Runtime.Persistence.Sqlite.csproj" />
    <ProjectReference Include="..\Madorin.AI.Runtime.Services\Madorin.AI.Runtime.Services.csproj" />
    <ProjectReference Include="..\Providers\Madorin.AI.Runtime.Providers.Abstractions\Madorin.AI.Runtime.Providers.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Madorin.AI.Runtime.Server" />
  </ItemGroup>

</Project>
