using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;

using Microsoft.Extensions.DependencyInjection;

using Netor.Cortana.AI.Workflow;
using Netor.Cortana.Entitys;
using Netor.Cortana.Entitys.Services;

namespace Netor.Cortana.UI.ViewModels.Workspace;

/// <summary>
/// 阶段 6 Phase 2：NewTaskDialog 高风险工具屏蔽项 ViewModel。
/// 决策 6-2-C：一期硬编码 4 项已知高风险插件 / 工具，未来可由插件 manifest 声明 riskLevel 字段动态生成。
/// 决策 6-2-A 黑名单 + 6-2-B 粒度 "pluginId" 整体屏蔽（也兼容 "pluginId:toolName" 细粒度）。
/// 详见 docs/未来版本策划/多智能体编排模式策划/04-实施阶段.md §阶段 6 #1。
/// </summary>
public sealed class HighRiskToolItem : INotifyPropertyChanged
{
    private bool _isBlocked;

    /// <summary>UI 显示名称（如 "C# 脚本执行"）。</summary>
    public string DisplayName { get; }

    /// <summary>黑名单元素值。pluginId 或 pluginId:toolName 格式（决策 6-2-B）。</summary>
    public string BlacklistKey { get; }

    /// <summary>UI ToolTip / 描述文本（解释该工具的风险类别）。</summary>
    public string Description { get; }

    /// <summary>用户是否勾选屏蔽。双向绑定到 CheckBox.IsChecked。</summary>
    public bool IsBlocked
    {
        get => _isBlocked;
        set
        {
            if (_isBlocked == value) return;
            _isBlocked = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(IsBlocked)));
        }
    }

    public HighRiskToolItem(string displayName, string blacklistKey, string description)
    {
        DisplayName = displayName;
        BlacklistKey = blacklistKey;
        Description = description;
    }

    public event PropertyChangedEventHandler? PropertyChanged;
}

/// <summary>
/// 阶段 3B：新建 Workflow 任务对话框的 ViewModel。
///
/// 职责：
/// - 维护表单字段（Title / SubMode / InitialInput / SelectedManager / SelectedMembers）
/// - 校验表单合法性（至少 2 个参与者，InitialInput 非空）
/// - 调用 <see cref="IWorkflowExecutor.StartTaskAsync"/> 启动任务
///
/// 决策 6-A：Title 字段可选；留空时自动占位 = InitialInput.Truncate(32)，并写入 IsTitleAutoGenerated=1。
///
/// 详见：docs/未来版本策划/多智能体编排模式策划/06-工作模式独立模块设计.md §5.2。
/// </summary>
public sealed class NewTaskDialogVm : INotifyPropertyChanged
{
    private readonly AgentService _agentService;
    private readonly IWorkflowExecutor _executor;
    private readonly SystemSettingsService _systemSettings;

    // 阶段 5B Phase 4：Magentic 成本估算缓存（从 SystemSettings 读取一次后缓存）
    // 详见 docs/未来版本策划/多智能体编排模式策划/04-实施阶段.md §5B.4。
    private readonly int _magenticEstimatedTokenMultiplier;
    private readonly int _magenticCostWarningThreshold;
    private const int MagenticDefaultMaxRounds = 8;   // 与 WorkflowExecutorOptions.MaxRounds 默认值保持同步

    private string _title = string.Empty;
    private string _subMode = "groupchat";
    private string _initialInput = string.Empty;
    private AgentEntity? _selectedManager;
    private string _workspaceId = string.Empty;
    private bool _isSubmitting;
    private string? _validationError;

    public NewTaskDialogVm()
    {
        _agentService = App.Services.GetRequiredService<AgentService>();
        _executor = App.Services.GetRequiredService<IWorkflowExecutor>();
        _systemSettings = App.Services.GetRequiredService<SystemSettingsService>();

        // 一次性读取 Magentic 成本警告配置（构造期固定值，对话框生命周期短，不订阅设置变更）
        _magenticEstimatedTokenMultiplier = _systemSettings.GetValue("Workflow.Magentic.EstimatedTokenMultiplier", 2000);
        _magenticCostWarningThreshold = _systemSettings.GetValue("Workflow.Magentic.CostWarningThreshold", 100000);

        // SelectedMembers 是 ObservableCollection，把集合变化映射到 CanSubmit + 成本相关属性的 PropertyChanged，
        // 让 View 层 IsEnabled 与警告 banner 实时更新（AOT 友好，无反射）。
        SelectedMembers.CollectionChanged += (_, _) =>
        {
            OnPropertyChanged(nameof(CanSubmit));
            OnPropertyChanged(nameof(EstimatedCost));
            OnPropertyChanged(nameof(EstimatedCostText));
            OnPropertyChanged(nameof(IsCostWarningVisible));
        };

        LoadAvailableAgents();
    }

    /// <summary>
    /// 让调用方（View 层 CheckBox 事件处理器）在集合变化外的场景显式触发 CanSubmit 重新计算。
    /// 用于 AOT 友好场景（避免反射调用 OnPropertyChanged）。
    /// </summary>
    public void NotifyCanSubmitChanged() => OnPropertyChanged(nameof(CanSubmit));

    // ──── 表单字段 ────

    public string Title
    {
        get => _title;
        set => SetField(ref _title, value);
    }

    /// <summary>子模式。3B 仅 "groupchat"；4B 起加 "magentic" / "parallelanalysis"。</summary>
    public string SubMode
    {
        get => _subMode;
        set
        {
            if (SetField(ref _subMode, value))
            {
                // 阶段 5B Phase 4：切到/离开 magentic 时刷新成本估算
                OnPropertyChanged(nameof(EstimatedCost));
                OnPropertyChanged(nameof(EstimatedCostText));
                OnPropertyChanged(nameof(IsCostWarningVisible));
            }
        }
    }

    public string InitialInput
    {
        get => _initialInput;
        set
        {
            if (SetField(ref _initialInput, value))
                OnPropertyChanged(nameof(CanSubmit));
        }
    }

    public AgentEntity? SelectedManager
    {
        get => _selectedManager;
        set
        {
            if (SetField(ref _selectedManager, value))
            {
                OnPropertyChanged(nameof(CanSubmit));
                // 阶段 5B Phase 4：Manager 变化也算参与者变化，刷新成本估算
                OnPropertyChanged(nameof(EstimatedCost));
                OnPropertyChanged(nameof(EstimatedCostText));
                OnPropertyChanged(nameof(IsCostWarningVisible));
            }
        }
    }

    public string WorkspaceId
    {
        get => _workspaceId;
        set => SetField(ref _workspaceId, value);
    }

    /// <summary>可选 Manager 智能体列表（DataContext = AgentEntity）。</summary>
    public ObservableCollection<AgentEntity> AvailableAgents { get; } = [];

    /// <summary>选中的 Member 智能体（双向绑定，用户多选）。</summary>
    public ObservableCollection<AgentEntity> SelectedMembers { get; } = [];

    /// <summary>
    /// 阶段 6 Phase 2：高风险工具屏蔽列表（一期硬编码 4 项，决策 6-2-C）。
    /// 用户在 NewTaskDialog 上勾选 CheckBox 即把对应 BlacklistKey 加入任务级黑名单。
    /// 后期由插件 manifest 声明 riskLevel 字段动态生成（推到阶段 7）。
    /// 详见 docs/未来版本策划/多智能体编排模式策划/04-实施阶段.md §阶段 6 #1。
    /// </summary>
    public ObservableCollection<HighRiskToolItem> HighRiskTools { get; } =
    [
        new HighRiskToolItem(
            "C# 脚本执行 (sys_csx_script)",
            "sys_csx_script",
            "可在 .NET Runtime 上执行任意 C# 代码，能调用 BCL 全部 API；屏蔽后本任务不会启用此插件。"),
        new HighRiskToolItem(
            "应用程序启动器 (sys_app_launcher)",
            "sys_app_launcher",
            "可启动本机任意可执行文件，可能导致进程注入或权限提升；屏蔽后本任务不会启动外部应用。"),
        new HighRiskToolItem(
            "窗口管理 (sys_window_manager)",
            "sys_window_manager",
            "可读取/操作其他应用的窗口与输入焦点；屏蔽后本任务不会跨进程操作窗口。"),
        new HighRiskToolItem(
            "Office 文档操作 (sys_office)",
            "sys_office",
            "可读写本机 Office 文档；屏蔽后本任务不会修改 .docx / .xlsx / .pptx 文件。"),
    ];

    public bool IsSubmitting
    {
        get => _isSubmitting;
        private set
        {
            if (SetField(ref _isSubmitting, value))
                OnPropertyChanged(nameof(CanSubmit));
        }
    }

    public string? ValidationError
    {
        get => _validationError;
        private set => SetField(ref _validationError, value);
    }

    /// <summary>
    /// 表单是否合法可提交（决策 [04] §3B.5）：
    /// - 至少 2 个 GroupChat 参与者（Manager + 至少 1 个 Member，或 2+ Members）
    /// - InitialInput 非空
    /// - 不在提交中
    /// </summary>
    public bool CanSubmit
    {
        get
        {
            if (_isSubmitting) return false;
            if (string.IsNullOrWhiteSpace(_initialInput)) return false;
            var count = (_selectedManager is null ? 0 : 1) + SelectedMembers.Count;
            return count >= 2;
        }
    }

    // ──── 阶段 5B Phase 4：Magentic 成本估算 ────

    /// <summary>
    /// 当前参与者总数（Manager + Members）。Magentic 通常需要 1 个 manager + N 个 specialist。
    /// </summary>
    private int ParticipantCount => (_selectedManager is null ? 0 : 1) + SelectedMembers.Count;

    /// <summary>
    /// 估算 token 消耗（仅 magentic 子模式有效，其它子模式返回 0）。
    /// 公式：MaxRounds × MagenticEstimatedTokenMultiplier × ParticipantCount
    /// 详见 04-实施阶段.md §5B.4 / 04 §4B.6。
    /// </summary>
    public long EstimatedCost
    {
        get
        {
            if (!string.Equals(_subMode, "magentic", StringComparison.OrdinalIgnoreCase)) return 0;
            if (ParticipantCount == 0) return 0;
            return (long)MagenticDefaultMaxRounds * _magenticEstimatedTokenMultiplier * ParticipantCount;
        }
    }

    /// <summary>UI 友好的成本展示文本（如 "约 128k tokens"）。</summary>
    public string EstimatedCostText
    {
        get
        {
            var cost = EstimatedCost;
            if (cost <= 0) return string.Empty;
            return cost >= 1000
                ? $"预计消耗约 {cost / 1000:N0}k tokens"
                : $"预计消耗约 {cost} tokens";
        }
    }

    /// <summary>
    /// 是否显示成本警告 banner：仅当 magentic 子模式 + 参与者已选 + 估算值 ≥ 阈值。
    /// 阈值 0 表示禁用警告（用户在 SystemSettings 中显式关闭）。
    /// </summary>
    public bool IsCostWarningVisible
    {
        get
        {
            if (_magenticCostWarningThreshold <= 0) return false;
            return EstimatedCost >= _magenticCostWarningThreshold;
        }
    }

    // ──── 加载/提交 ────

    private void LoadAvailableAgents()
    {
        var agents = _agentService.GetAll();
        AvailableAgents.Clear();
        foreach (var a in agents) AvailableAgents.Add(a);
    }

    /// <summary>
    /// 提交表单：调用 <see cref="IWorkflowExecutor.StartTaskAsync"/> 启动任务。
    /// 成功返回 taskId；失败返回 null 且设置 <see cref="ValidationError"/>。
    /// </summary>
    public async Task<string?> SubmitAsync(CancellationToken cancellationToken)
    {
        if (!CanSubmit)
        {
            ValidationError = "请填写任务描述并选择至少 2 个参与者";
            return null;
        }

        IsSubmitting = true;
        ValidationError = null;
        try
        {
            var memberIds = SelectedMembers.Select(m => m.Id).ToList();

            // 阶段 6 Phase 2：收集用户勾选的高风险工具屏蔽项（决策 6-2-A 黑名单 + 6-2-B "pluginId" 粒度）。
            // 空列表传 null，让 WorkflowTaskRequest.ToolBlacklist 保持 null，
            // 后端 InsertTaskAndParticipants 会跳过 ToolBlacklistJson 序列化（向后兼容旧任务）。
            List<string>? blacklist = null;
            foreach (var tool in HighRiskTools)
            {
                if (tool.IsBlocked)
                {
                    blacklist ??= [];
                    blacklist.Add(tool.BlacklistKey);
                }
            }

            var request = new WorkflowTaskRequest
            {
                Title = string.IsNullOrWhiteSpace(_title) ? null : _title.Trim(),
                Mode = "discussion",
                SubMode = _subMode,
                InitialInput = _initialInput.Trim(),
                WorkspaceId = _workspaceId ?? string.Empty,
                CreatedBy = "user",
                ManagerAgentId = _selectedManager?.Id,
                ManagerAgentName = _selectedManager?.Name,
                MemberAgentIds = memberIds,
                ToolBlacklist = blacklist,   // 阶段 6 Phase 2
            };

            var taskId = await _executor.StartTaskAsync(request, cancellationToken);
            return taskId;
        }
        catch (Exception ex)
        {
            ValidationError = $"启动任务失败：{ex.Message}";
            return null;
        }
        finally
        {
            IsSubmitting = false;
        }
    }

    // ──── INotifyPropertyChanged ────

    public event PropertyChangedEventHandler? PropertyChanged;

    private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

    private bool SetField<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value)) return false;
        field = value;
        OnPropertyChanged(propertyName);
        return true;
    }
}
