using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;

using Microsoft.Extensions.DependencyInjection;

using Netor.Cortana.AI.Workflow;
using Netor.Cortana.Entitys;
using Netor.Cortana.Entitys.Services;

namespace Netor.Cortana.UI.ViewModels.Workspace;

/// <summary>
/// 阶段 3B：新建 Workflow 任务对话框的 ViewModel。
///
/// 职责：
/// - 维护表单字段（Title / SubMode / InitialInput / SelectedManager / SelectedMembers）
/// - 校验表单合法性（至少 2 个参与者，InitialInput 非空）
/// - 调用 <see cref="IWorkflowExecutor.StartTaskAsync"/> 启动任务
///
/// 决策 6-A：Title 字段可选；留空时自动占位 = InitialInput.Truncate(32)，并写入 IsTitleAutoGenerated=1。
///
/// 详见：docs/未来版本策划/多智能体编排模式策划/06-工作模式独立模块设计.md §5.2。
/// </summary>
public sealed class NewTaskDialogVm : INotifyPropertyChanged
{
    private readonly AgentService _agentService;
    private readonly IWorkflowExecutor _executor;

    private string _title = string.Empty;
    private string _subMode = "groupchat";
    private string _initialInput = string.Empty;
    private AgentEntity? _selectedManager;
    private string _workspaceId = string.Empty;
    private bool _isSubmitting;
    private string? _validationError;

    public NewTaskDialogVm()
    {
        _agentService = App.Services.GetRequiredService<AgentService>();
        _executor = App.Services.GetRequiredService<IWorkflowExecutor>();

        // SelectedMembers 是 ObservableCollection，把集合变化映射到 CanSubmit 的 PropertyChanged，
        // 让 View 层 IsEnabled 实时更新（AOT 友好，无反射）。
        SelectedMembers.CollectionChanged += (_, _) => OnPropertyChanged(nameof(CanSubmit));

        LoadAvailableAgents();
    }

    /// <summary>
    /// 让调用方（View 层 CheckBox 事件处理器）在集合变化外的场景显式触发 CanSubmit 重新计算。
    /// 用于 AOT 友好场景（避免反射调用 OnPropertyChanged）。
    /// </summary>
    public void NotifyCanSubmitChanged() => OnPropertyChanged(nameof(CanSubmit));

    // ──── 表单字段 ────

    public string Title
    {
        get => _title;
        set => SetField(ref _title, value);
    }

    /// <summary>子模式。3B 仅 "groupchat"；4B 起加 "magentic" / "parallelanalysis"。</summary>
    public string SubMode
    {
        get => _subMode;
        set => SetField(ref _subMode, value);
    }

    public string InitialInput
    {
        get => _initialInput;
        set
        {
            if (SetField(ref _initialInput, value))
                OnPropertyChanged(nameof(CanSubmit));
        }
    }

    public AgentEntity? SelectedManager
    {
        get => _selectedManager;
        set
        {
            if (SetField(ref _selectedManager, value))
                OnPropertyChanged(nameof(CanSubmit));
        }
    }

    public string WorkspaceId
    {
        get => _workspaceId;
        set => SetField(ref _workspaceId, value);
    }

    /// <summary>可选 Manager 智能体列表（DataContext = AgentEntity）。</summary>
    public ObservableCollection<AgentEntity> AvailableAgents { get; } = [];

    /// <summary>选中的 Member 智能体（双向绑定，用户多选）。</summary>
    public ObservableCollection<AgentEntity> SelectedMembers { get; } = [];

    public bool IsSubmitting
    {
        get => _isSubmitting;
        private set
        {
            if (SetField(ref _isSubmitting, value))
                OnPropertyChanged(nameof(CanSubmit));
        }
    }

    public string? ValidationError
    {
        get => _validationError;
        private set => SetField(ref _validationError, value);
    }

    /// <summary>
    /// 表单是否合法可提交（决策 [04] §3B.5）：
    /// - 至少 2 个 GroupChat 参与者（Manager + 至少 1 个 Member，或 2+ Members）
    /// - InitialInput 非空
    /// - 不在提交中
    /// </summary>
    public bool CanSubmit
    {
        get
        {
            if (_isSubmitting) return false;
            if (string.IsNullOrWhiteSpace(_initialInput)) return false;
            var count = (_selectedManager is null ? 0 : 1) + SelectedMembers.Count;
            return count >= 2;
        }
    }

    // ──── 加载/提交 ────

    private void LoadAvailableAgents()
    {
        var agents = _agentService.GetAll();
        AvailableAgents.Clear();
        foreach (var a in agents) AvailableAgents.Add(a);
    }

    /// <summary>
    /// 提交表单：调用 <see cref="IWorkflowExecutor.StartTaskAsync"/> 启动任务。
    /// 成功返回 taskId；失败返回 null 且设置 <see cref="ValidationError"/>。
    /// </summary>
    public async Task<string?> SubmitAsync(CancellationToken cancellationToken)
    {
        if (!CanSubmit)
        {
            ValidationError = "请填写任务描述并选择至少 2 个参与者";
            return null;
        }

        IsSubmitting = true;
        ValidationError = null;
        try
        {
            var memberIds = SelectedMembers.Select(m => m.Id).ToList();

            var request = new WorkflowTaskRequest
            {
                Title = string.IsNullOrWhiteSpace(_title) ? null : _title.Trim(),
                Mode = "discussion",
                SubMode = _subMode,
                InitialInput = _initialInput.Trim(),
                WorkspaceId = _workspaceId ?? string.Empty,
                CreatedBy = "user",
                ManagerAgentId = _selectedManager?.Id,
                ManagerAgentName = _selectedManager?.Name,
                MemberAgentIds = memberIds,
            };

            var taskId = await _executor.StartTaskAsync(request, cancellationToken);
            return taskId;
        }
        catch (Exception ex)
        {
            ValidationError = $"启动任务失败：{ex.Message}";
            return null;
        }
        finally
        {
            IsSubmitting = false;
        }
    }

    // ──── INotifyPropertyChanged ────

    public event PropertyChangedEventHandler? PropertyChanged;

    private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

    private bool SetField<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value)) return false;
        field = value;
        OnPropertyChanged(propertyName);
        return true;
    }
}
