using System.ComponentModel;
using System.Runtime.CompilerServices;

using Netor.Cortana.AI.TaskEngine.Models;

namespace Netor.Cortana.UI.ViewModels.Workspace;

/// <summary>
/// P4 过渡：任务状态枚举（替代已删除的 Netor.Cortana.AI.Workflow.WorkflowTaskStatus）。
/// </summary>
public enum TaskItemStatus
{
    Pending,
    Running,
    Paused,
    Completed,
    Failed,
    Cancelled,
}

/// <summary>
/// P4 过渡：TaskItemStatus 与 DB string 值互转工具类（替代已删除的 WorkflowTaskStatusExtensions）。
/// </summary>
public static class TaskItemStatusExtensions
{
    public static TaskItemStatus FromDbValue(string? dbValue) => dbValue switch
    {
        "running" => TaskItemStatus.Running,
        "paused" => TaskItemStatus.Paused,
        "completed" => TaskItemStatus.Completed,
        "failed" => TaskItemStatus.Failed,
        "cancelled" => TaskItemStatus.Cancelled,
        _ => TaskItemStatus.Pending,
    };

    public static string ToDbValue(this TaskItemStatus status) => status switch
    {
        TaskItemStatus.Running => "running",
        TaskItemStatus.Paused => "paused",
        TaskItemStatus.Completed => "completed",
        TaskItemStatus.Failed => "failed",
        TaskItemStatus.Cancelled => "cancelled",
        _ => "pending",
    };
}

/// <summary>
/// 阶段 3B：单条 Workflow 任务列表项的 ViewModel。
/// 实现 <see cref="INotifyPropertyChanged"/>，当 Title / Status / LastActiveTimestamp 变化时
/// 触发 View 层单点刷新（仅 1 处 TextBlock 更新，满足 [06] §5.8.7 验收）。
///
/// 不订阅事件，仅作为数据载体；订阅由 <see cref="WorkflowTaskListVm"/> 统一处理。
/// </summary>
public sealed class WorkflowTaskItemVm : INotifyPropertyChanged
{
    private string _title = string.Empty;
    private bool _isTitleAutoGenerated;
    private TaskItemStatus _status;
    private long _lastActiveTimestamp;
    private bool _isPinned;

    /// <summary>
    /// P4 构造：从 TaskExecutionEngine.ListTasksAsync 返回的 TaskStatusInfo 构造列表项。
    /// </summary>
    public WorkflowTaskItemVm(TaskStatusInfo info)
    {
        ArgumentNullException.ThrowIfNull(info);
        TaskId = info.TaskId;
        SubMode = "magentic"; // P4 任务默认子模式
        StartedAt = info.StartedAt.ToUnixTimeMilliseconds();
        _title = info.Title ?? string.Empty;
        _isTitleAutoGenerated = string.IsNullOrEmpty(info.Title);
        _status = TaskItemStatusExtensions.FromDbValue(info.Status);
        _lastActiveTimestamp = info.StartedAt.ToUnixTimeMilliseconds();
        _isPinned = false;
    }

    /// <summary>任务 ID（只读）。</summary>
    public string TaskId { get; }

    /// <summary>任务子模式（如 "groupchat"）。</summary>
    public string SubMode { get; }

    /// <summary>任务开始时间（Unix ms）。</summary>
    public long StartedAt { get; }

    /// <summary>任务标题（可能由 LLM 异步兜底更新）。</summary>
    public string Title
    {
        get => _title;
        set => SetField(ref _title, value);
    }

    /// <summary>是否占位标题（灰色显示）。</summary>
    public bool IsTitleAutoGenerated
    {
        get => _isTitleAutoGenerated;
        set
        {
            if (SetField(ref _isTitleAutoGenerated, value))
            {
                OnPropertyChanged(nameof(DisplayTitle));
                OnPropertyChanged(nameof(IsTitlePlaceholder));
            }
        }
    }

    /// <summary>任务状态。</summary>
    public TaskItemStatus Status
    {
        get => _status;
        set
        {
            if (SetField(ref _status, value))
            {
                OnPropertyChanged(nameof(StatusIcon));
                OnPropertyChanged(nameof(StatusColorHex));
            }
        }
    }

    /// <summary>最后活跃时间（Unix ms），用于排序。</summary>
    public long LastActiveTimestamp
    {
        get => _lastActiveTimestamp;
        set
        {
            if (SetField(ref _lastActiveTimestamp, value))
                OnPropertyChanged(nameof(RelativeTimeText));
        }
    }

    /// <summary>是否置顶。</summary>
    public bool IsPinned
    {
        get => _isPinned;
        set => SetField(ref _isPinned, value);
    }

    // ──── 派生只读属性（用于 Binding 显示）────

    /// <summary>显示用标题：占位时为"占位中..."，否则为 Title。</summary>
    public string DisplayTitle
        => string.IsNullOrEmpty(_title) && _isTitleAutoGenerated ? "占位中..." : _title;

    /// <summary>是否处于占位状态（控件可基于此切换灰色样式）。</summary>
    public bool IsTitlePlaceholder
        => string.IsNullOrEmpty(_title) && _isTitleAutoGenerated;

    /// <summary>状态图标字符（[06] §5.1）。</summary>
    public string StatusIcon => _status switch
    {
        TaskItemStatus.Pending or TaskItemStatus.Running => "●",
        TaskItemStatus.Paused => "⏸",
        TaskItemStatus.Completed => "✓",
        TaskItemStatus.Failed => "✕",
        TaskItemStatus.Cancelled => "⊘",
        _ => "?",
    };

    /// <summary>状态颜色（用于绑定 Foreground）。</summary>
    public string StatusColorHex => _status switch
    {
        TaskItemStatus.Pending or TaskItemStatus.Running => "#3794ff",   // 蓝
        TaskItemStatus.Paused => "#d7ba7d",                                  // 黄
        TaskItemStatus.Completed => "#73c991",                               // 绿
        TaskItemStatus.Failed => "#f48771",                                  // 红
        TaskItemStatus.Cancelled => "#858585",                               // 灰
        _ => "#858585",
    };

    /// <summary>相对时间文本（"3:24 前" / "昨天" / "2 分钟前"），用于绑定显示。</summary>
    public string RelativeTimeText
    {
        get
        {
            var dt = DateTimeOffset.FromUnixTimeMilliseconds(_lastActiveTimestamp).LocalDateTime;
            var span = DateTime.Now - dt;
            return span.TotalSeconds < 60 ? "刚刚"
                : span.TotalMinutes < 60 ? $"{(int)span.TotalMinutes} 分钟前"
                : span.TotalHours < 24 ? $"{(int)span.TotalHours} 小时前"
                : span.TotalDays < 2 ? "昨天"
                : span.TotalDays < 7 ? $"{(int)span.TotalDays} 天前"
                : dt.ToString("MM-dd");
        }
    }

    // ──── INotifyPropertyChanged ────

    public event PropertyChangedEventHandler? PropertyChanged;

    private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

    private bool SetField<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value)) return false;
        field = value;
        OnPropertyChanged(propertyName);
        return true;
    }
}
