using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;

using Netor.Cortana.AI.Providers;
using Netor.Cortana.Entitys;
using Netor.Cortana.Entitys.Extensions;
using Netor.Cortana.Entitys.Services;
using Netor.EventHub;

namespace Netor.Cortana.AI.Workflow.Title;

/// <summary>
/// 默认 <see cref="IWorkflowTitleGenerator"/> 实现。
/// 与 <see cref="ChatHistoryDataProvider"/>.GenerateAndUpdateTitleAsync 同模式：
/// 1. 通过 <see cref="IChatCompactionClientResolver"/> 解析压缩客户端；
/// 2. 用 (client as TokenTrackingChatClient)?.SuppressUsage() 隔离 token 上报；
/// 3. 调用 LLM 生成短标题；
/// 4. 写库 + 发 OnWorkflowTaskTitleUpdated 事件。
/// </summary>
public sealed class WorkflowTitleGenerator(
    IChatCompactionClientResolver compactionResolver,
    WorkflowTaskRepository taskRepo,
    IPublisher publisher,
    ILogger<WorkflowTitleGenerator> logger) : IWorkflowTitleGenerator
{
    public async Task GenerateAndUpdateTitleAsync(
        AIAgent agent,
        string taskId,
        string initialInput,
        string? finalReport,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(agent);
        if (string.IsNullOrWhiteSpace(taskId)) return;

        try
        {
            var client = compactionResolver.Resolve(agent);
            if (client is null)
            {
                logger.LogDebug("Workflow 任务 {TaskId} 无可用压缩客户端，跳过标题生成。", taskId);
                return;
            }

            // 取出当前任务以便填 oldTitle / 判断是否需要兜底
            var taskBefore = taskRepo.GetById(taskId);
            if (taskBefore is null) return;

            // 用户已经提供了非自动生成的标题 → 不再覆盖
            if (!taskBefore.IsTitleAutoGenerated && !string.IsNullOrWhiteSpace(taskBefore.Title))
            {
                return;
            }

            var prompt = new List<ChatMessage>
            {
                new(ChatRole.System,
                    "你是任务标题生成助手。根据用户的任务描述与执行报告，提取关键信息生成一个简短任务标题。" +
                    "要求：不超过 20 个字，不要引号，不要标点，直接输出标题文本。"),
                new(ChatRole.User,
                    $"任务描述：{initialInput.Truncate(200)}\n" +
                    (string.IsNullOrEmpty(finalReport)
                        ? string.Empty
                        : $"执行报告摘要：{finalReport.Truncate(500)}")),
            };

            // 抑制 usage 上报，避免污染主对话进度条
            using var _ = (client as TokenTrackingChatClient)?.SuppressUsage();
            var completion = await client.GetResponseAsync(prompt, cancellationToken: cancellationToken);
            var title = completion?.Text?.Trim();

            if (string.IsNullOrWhiteSpace(title)) return;

            title = title.Trim('"', '"', '"', '「', '」', '\'').Truncate(32);

            taskRepo.UpdateTitle(taskId, title, isAutoGenerated: true);

            publisher.Publish(Events.OnWorkflowTaskTitleUpdated, new WorkflowTaskTitleUpdatedArgs(
                TaskId: taskId,
                SourceSessionId: taskBefore.SourceSessionId,
                TraceId: taskBefore.TraceId,
                WorkspaceId: taskBefore.WorkspaceId,
                Mode: taskBefore.Mode,
                SubMode: taskBefore.SubMode,
                OccurredAt: DateTimeOffset.UtcNow,
                OldTitle: taskBefore.Title ?? string.Empty,
                NewTitle: title,
                IsAutoGenerated: true));

            logger.LogInformation("Workflow 任务 {TaskId} 标题已由 AI 生成：{Title}", taskId, title);
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            logger.LogWarning(ex, "为 Workflow 任务 {TaskId} 生成 AI 标题失败，保留原标题。", taskId);
        }
    }
}
