// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Database.Abstractions;
using Netor.Database.Abstractions.Enums;
using Netor.Database.Abstractions.Interface;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class AccountPropertyBaseUnsafeAccessors<TAccount>
        where TAccount : Base, IAccount
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Display>k__BackingField")]
        public static extern ref string Display(AccountPropertyBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Group>k__BackingField")]
        public static extern ref string Group(AccountPropertyBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Key>k__BackingField")]
        public static extern ref string Key(AccountPropertyBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref NetorDataType Type(AccountPropertyBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Value>k__BackingField")]
        public static extern ref string Value(AccountPropertyBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref TAccount Account(AccountPropertyBase<TAccount> @this);
    }
}
