// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Database.Abstractions;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class AccountBaseUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AccountType>k__BackingField")]
        public static extern ref byte AccountType(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Email>k__BackingField")]
        public static extern ref string Email(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EmailConfirmed>k__BackingField")]
        public static extern ref bool EmailConfirmed(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Image>k__BackingField")]
        public static extern ref string Image(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastLoginTime>k__BackingField")]
        public static extern ref DateTime LastLoginTime(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LoginIP>k__BackingField")]
        public static extern ref string LoginIP(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LoginPassword>k__BackingField")]
        public static extern ref string LoginPassword(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LoginTimes>k__BackingField")]
        public static extern ref int LoginTimes(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LoginUserName>k__BackingField")]
        public static extern ref string LoginUserName(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NickName>k__BackingField")]
        public static extern ref string NickName(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<No>k__BackingField")]
        public static extern ref long No(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Phone>k__BackingField")]
        public static extern ref string Phone(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PhoneConfirmed>k__BackingField")]
        public static extern ref bool PhoneConfirmed(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RealName>k__BackingField")]
        public static extern ref string RealName(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Refer>k__BackingField")]
        public static extern ref string Refer(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RegestorIP>k__BackingField")]
        public static extern ref string RegestorIP(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SafePassword>k__BackingField")]
        public static extern ref string SafePassword(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Sex>k__BackingField")]
        public static extern ref byte Sex(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SingleLoginEnabled>k__BackingField")]
        public static extern ref bool SingleLoginEnabled(AccountBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
        public static extern ref byte Status(AccountBase @this);
    }
}
