// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Database.Abstractions;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class AccountLayerUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ID>k__BackingField")]
        public static extern ref long ID(AccountLayer @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AccountNo>k__BackingField")]
        public static extern ref long AccountNo(AccountLayer @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Index>k__BackingField")]
        public static extern ref long Index(AccountLayer @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParentNo>k__BackingField")]
        public static extern ref long ParentNo(AccountLayer @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Timestamp>k__BackingField")]
        public static extern ref long Timestamp(AccountLayer @this);
    }
}
