// <auto-generated />
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Tables.Accounts;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class AccountUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Properties>k__BackingField")]
        public static extern ref ICollection<AccountProperty> Properties(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RolePairs>k__BackingField")]
        public static extern ref ICollection<AccountRolePair> RolePairs(Account @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Wallets>k__BackingField")]
        public static extern ref ICollection<AccountWallet> Wallets(Account @this);
    }
}
