// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Enums;
using Netor.Cortana.Platform.Entitys.Tables.Accounts;
using Netor.Cortana.Platform.Entitys.Tables.Assets;
using Netor.Cortana.Platform.Entitys.Tables.Reviews;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class AssetReviewUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AssetId>k__BackingField")]
        public static extern ref string AssetId(AssetReview @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AssetVersionId>k__BackingField")]
        public static extern ref string AssetVersionId(AssetReview @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
        public static extern ref string Notes(AssetReview @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ReviewedAtUtc>k__BackingField")]
        public static extern ref DateTimeOffset? ReviewedAtUtc(AssetReview @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ReviewerId>k__BackingField")]
        public static extern ref string ReviewerId(AssetReview @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
        public static extern ref AssetReviewStatus Status(AssetReview @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SubmitterAccountId>k__BackingField")]
        public static extern ref string SubmitterAccountId(AssetReview @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Asset>k__BackingField")]
        public static extern ref Asset Asset(AssetReview @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AssetVersion>k__BackingField")]
        public static extern ref AssetVersion AssetVersion(AssetReview @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SubmitterAccount>k__BackingField")]
        public static extern ref Account SubmitterAccount(AssetReview @this);
    }
}
