// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Tables.Assets;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class CategoryUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(Category @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsVisible>k__BackingField")]
        public static extern ref bool IsVisible(Category @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(Category @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Slug>k__BackingField")]
        public static extern ref string Slug(Category @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SortOrder>k__BackingField")]
        public static extern ref int SortOrder(Category @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Assets>k__BackingField")]
        public static extern ref ICollection<Asset> Assets(Category @this);
    }
}
