// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Enums;
using Netor.Cortana.Platform.Entitys.Tables.Accounts;
using Netor.Cortana.Platform.Entitys.Tables.Assets;
using Netor.Cortana.Platform.Entitys.Tables.Orders;
using Netor.Cortana.Platform.Entitys.Tables.Settlements;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class CreatorSettlementUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AssetId>k__BackingField")]
        public static extern ref string AssetId(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatorAccountId>k__BackingField")]
        public static extern ref string CreatorAccountId(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Currency>k__BackingField")]
        public static extern ref string Currency(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GrossAmount>k__BackingField")]
        public static extern ref decimal GrossAmount(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<NetAmount>k__BackingField")]
        public static extern ref decimal NetAmount(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Notes>k__BackingField")]
        public static extern ref string Notes(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OrderId>k__BackingField")]
        public static extern ref string OrderId(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PlatformFeeAmount>k__BackingField")]
        public static extern ref decimal PlatformFeeAmount(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SettledAtUtc>k__BackingField")]
        public static extern ref DateTimeOffset? SettledAtUtc(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
        public static extern ref SettlementStatus Status(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Asset>k__BackingField")]
        public static extern ref Asset Asset(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatorAccount>k__BackingField")]
        public static extern ref Account CreatorAccount(CreatorSettlement @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Order>k__BackingField")]
        public static extern ref Order Order(CreatorSettlement @this);
    }
}
