// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Enums;
using Netor.Cortana.Platform.Entitys.Tables.Accounts;
using Netor.Cortana.Platform.Entitys.Tables.Creators;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class CreatorProfileUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AccountId>k__BackingField")]
        public static extern ref string AccountId(CreatorProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ApprovedAtUtc>k__BackingField")]
        public static extern ref DateTimeOffset? ApprovedAtUtc(CreatorProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Bio>k__BackingField")]
        public static extern ref string Bio(CreatorProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DisplayName>k__BackingField")]
        public static extern ref string DisplayName(CreatorProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
        public static extern ref CreatorStatus Status(CreatorProfile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref Account Account(CreatorProfile @this);
    }
}
