// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Tables.Accounts;
using Netor.Cortana.Platform.Entitys.Tables.Assets;
using Netor.Cortana.Platform.Entitys.Tables.Downloads;
using Netor.Cortana.Platform.Entitys.Tables.Subscriptions;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class DownloadRecordUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AccountId>k__BackingField")]
        public static extern ref string AccountId(DownloadRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AssetId>k__BackingField")]
        public static extern ref string AssetId(DownloadRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AssetVersionId>k__BackingField")]
        public static extern ref string AssetVersionId(DownloadRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IpAddress>k__BackingField")]
        public static extern ref string IpAddress(DownloadRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SubscriptionId>k__BackingField")]
        public static extern ref string SubscriptionId(DownloadRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserAgent>k__BackingField")]
        public static extern ref string UserAgent(DownloadRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref Account Account(DownloadRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Asset>k__BackingField")]
        public static extern ref Asset Asset(DownloadRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AssetVersion>k__BackingField")]
        public static extern ref AssetVersion AssetVersion(DownloadRecord @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Subscription>k__BackingField")]
        public static extern ref Subscription Subscription(DownloadRecord @this);
    }
}
