// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Tables.Managers;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class ManagerMcpTokenUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedUtc>k__BackingField")]
        public static extern ref DateTimeOffset CreatedUtc(ManagerMcpToken @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Enabled>k__BackingField")]
        public static extern ref bool Enabled(ManagerMcpToken @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastUsedIp>k__BackingField")]
        public static extern ref string LastUsedIp(ManagerMcpToken @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastUsedUa>k__BackingField")]
        public static extern ref string LastUsedUa(ManagerMcpToken @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastUsedUtc>k__BackingField")]
        public static extern ref DateTimeOffset? LastUsedUtc(ManagerMcpToken @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ManagerId>k__BackingField")]
        public static extern ref string ManagerId(ManagerMcpToken @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Note>k__BackingField")]
        public static extern ref string Note(ManagerMcpToken @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TokenHash>k__BackingField")]
        public static extern ref string TokenHash(ManagerMcpToken @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TokenPrefix>k__BackingField")]
        public static extern ref string TokenPrefix(ManagerMcpToken @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Manager>k__BackingField")]
        public static extern ref Manager Manager(ManagerMcpToken @this);
    }
}
