// <auto-generated />
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Tables.Managers;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class ManagerUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Properties>k__BackingField")]
        public static extern ref ICollection<ManagerProperty> Properties(Manager @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Role>k__BackingField")]
        public static extern ref ManagerRole Role(Manager @this);
    }
}
