// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Tables.Managers;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class ManagerAuditLogUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedUtc>k__BackingField")]
        public static extern ref DateTimeOffset CreatedUtc(ManagerAuditLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DurationMs>k__BackingField")]
        public static extern ref int DurationMs(ManagerAuditLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ErrorCode>k__BackingField")]
        public static extern ref string ErrorCode(ManagerAuditLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Ip>k__BackingField")]
        public static extern ref string Ip(ManagerAuditLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ManagerId>k__BackingField")]
        public static extern ref string ManagerId(ManagerAuditLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<SourceName>k__BackingField")]
        public static extern ref string SourceName(ManagerAuditLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Success>k__BackingField")]
        public static extern ref bool Success(ManagerAuditLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TokenId>k__BackingField")]
        public static extern ref string TokenId(ManagerAuditLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ToolName>k__BackingField")]
        public static extern ref string ToolName(ManagerAuditLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Ua>k__BackingField")]
        public static extern ref string Ua(ManagerAuditLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Manager>k__BackingField")]
        public static extern ref Manager Manager(ManagerAuditLog @this);
    }
}
