// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Database.Abstractions;
using Netor.Database.Abstractions.Interface;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class OrderBaseUnsafeAccessors<TAccount>
        where TAccount : Base, IAccount
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Money>k__BackingField")]
        public static extern ref decimal Money(OrderBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<No>k__BackingField")]
        public static extern ref string No(OrderBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Numbers>k__BackingField")]
        public static extern ref int Numbers(OrderBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PayMethod>k__BackingField")]
        public static extern ref byte PayMethod(OrderBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PayStatus>k__BackingField")]
        public static extern ref byte PayStatus(OrderBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PayTime>k__BackingField")]
        public static extern ref DateTime? PayTime(OrderBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
        public static extern ref byte Status(OrderBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Title>k__BackingField")]
        public static extern ref string Title(OrderBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref TAccount Account(OrderBase<TAccount> @this);
    }
}
