// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Tables.Orders;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class OrderUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AssetId>k__BackingField")]
        public static extern ref string AssetId(Order @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Content>k__BackingField")]
        public static extern ref string Content(Order @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PricingPlanId>k__BackingField")]
        public static extern ref string PricingPlanId(Order @this);
    }
}
