// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public partial class PlatformDbContextModel
    {
        private PlatformDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("0e419a4a-fcbc-4ab3-8aaa-1d32ccb3eece"), entityTypeCount: 26)
        {
        }

        partial void Initialize()
        {
            var account = AccountEntityType.Create(this);
            var accountProperty = AccountPropertyEntityType.Create(this);
            var accountRole = AccountRoleEntityType.Create(this);
            var accountRolePair = AccountRolePairEntityType.Create(this);
            var accountWallet = AccountWalletEntityType.Create(this);
            var asset = AssetEntityType.Create(this);
            var assetVersion = AssetVersionEntityType.Create(this);
            var category = CategoryEntityType.Create(this);
            var pricingPlan = PricingPlanEntityType.Create(this);
            var creatorProfile = CreatorProfileEntityType.Create(this);
            var docArticle = DocArticleEntityType.Create(this);
            var docCategory = DocCategoryEntityType.Create(this);
            var downloadRecord = DownloadRecordEntityType.Create(this);
            var idempotencyRecord = IdempotencyRecordEntityType.Create(this);
            var manager = ManagerEntityType.Create(this);
            var managerAuditLog = ManagerAuditLogEntityType.Create(this);
            var managerMcpToken = ManagerMcpTokenEntityType.Create(this);
            var managerProperty = ManagerPropertyEntityType.Create(this);
            var managerRole = ManagerRoleEntityType.Create(this);
            var order = OrderEntityType.Create(this);
            var transaction = TransactionEntityType.Create(this);
            var assetReview = AssetReviewEntityType.Create(this);
            var creatorSettlement = CreatorSettlementEntityType.Create(this);
            var subscription = SubscriptionEntityType.Create(this);
            var accountLayer = AccountLayerEntityType.Create(this);
            var systemSetting = SystemSettingEntityType.Create(this);

            AccountPropertyEntityType.CreateForeignKey1(accountProperty, account);
            AccountRolePairEntityType.CreateForeignKey1(accountRolePair, account);
            AccountRolePairEntityType.CreateForeignKey2(accountRolePair, accountRole);
            AccountWalletEntityType.CreateForeignKey1(accountWallet, account);
            AssetEntityType.CreateForeignKey1(asset, category);
            AssetEntityType.CreateForeignKey2(asset, account);
            AssetVersionEntityType.CreateForeignKey1(assetVersion, asset);
            PricingPlanEntityType.CreateForeignKey1(pricingPlan, asset);
            CreatorProfileEntityType.CreateForeignKey1(creatorProfile, account);
            DocArticleEntityType.CreateForeignKey1(docArticle, docCategory);
            DownloadRecordEntityType.CreateForeignKey1(downloadRecord, account);
            DownloadRecordEntityType.CreateForeignKey2(downloadRecord, asset);
            DownloadRecordEntityType.CreateForeignKey3(downloadRecord, assetVersion);
            DownloadRecordEntityType.CreateForeignKey4(downloadRecord, subscription);
            ManagerEntityType.CreateForeignKey1(manager, managerRole);
            ManagerAuditLogEntityType.CreateForeignKey1(managerAuditLog, manager);
            ManagerMcpTokenEntityType.CreateForeignKey1(managerMcpToken, manager);
            ManagerPropertyEntityType.CreateForeignKey1(managerProperty, manager);
            OrderEntityType.CreateForeignKey1(order, account);
            TransactionEntityType.CreateForeignKey1(transaction, account);
            AssetReviewEntityType.CreateForeignKey1(assetReview, asset);
            AssetReviewEntityType.CreateForeignKey2(assetReview, assetVersion);
            AssetReviewEntityType.CreateForeignKey3(assetReview, account);
            CreatorSettlementEntityType.CreateForeignKey1(creatorSettlement, asset);
            CreatorSettlementEntityType.CreateForeignKey2(creatorSettlement, account);
            CreatorSettlementEntityType.CreateForeignKey3(creatorSettlement, order);
            SubscriptionEntityType.CreateForeignKey1(subscription, account);
            SubscriptionEntityType.CreateForeignKey2(subscription, asset);
            SubscriptionEntityType.CreateForeignKey3(subscription, order);
            SubscriptionEntityType.CreateForeignKey4(subscription, pricingPlan);

            AccountEntityType.CreateAnnotations(account);
            AccountPropertyEntityType.CreateAnnotations(accountProperty);
            AccountRoleEntityType.CreateAnnotations(accountRole);
            AccountRolePairEntityType.CreateAnnotations(accountRolePair);
            AccountWalletEntityType.CreateAnnotations(accountWallet);
            AssetEntityType.CreateAnnotations(asset);
            AssetVersionEntityType.CreateAnnotations(assetVersion);
            CategoryEntityType.CreateAnnotations(category);
            PricingPlanEntityType.CreateAnnotations(pricingPlan);
            CreatorProfileEntityType.CreateAnnotations(creatorProfile);
            DocArticleEntityType.CreateAnnotations(docArticle);
            DocCategoryEntityType.CreateAnnotations(docCategory);
            DownloadRecordEntityType.CreateAnnotations(downloadRecord);
            IdempotencyRecordEntityType.CreateAnnotations(idempotencyRecord);
            ManagerEntityType.CreateAnnotations(manager);
            ManagerAuditLogEntityType.CreateAnnotations(managerAuditLog);
            ManagerMcpTokenEntityType.CreateAnnotations(managerMcpToken);
            ManagerPropertyEntityType.CreateAnnotations(managerProperty);
            ManagerRoleEntityType.CreateAnnotations(managerRole);
            OrderEntityType.CreateAnnotations(order);
            TransactionEntityType.CreateAnnotations(transaction);
            AssetReviewEntityType.CreateAnnotations(assetReview);
            CreatorSettlementEntityType.CreateAnnotations(creatorSettlement);
            SubscriptionEntityType.CreateAnnotations(subscription);
            AccountLayerEntityType.CreateAnnotations(accountLayer);
            SystemSettingEntityType.CreateAnnotations(systemSetting);

            AddAnnotation("ProductVersion", "10.0.8");
        }
    }
}
