// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Netor.Cortana.Platform.Entitys.Data;
using Netor.Cortana.Platform.Entitys.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(PlatformDbContext), typeof(PlatformDbContextModel))]
