// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Enums;
using Netor.Cortana.Platform.Entitys.Tables.Assets;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class PricingPlanUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AssetId>k__BackingField")]
        public static extern ref string AssetId(PricingPlan @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Currency>k__BackingField")]
        public static extern ref string Currency(PricingPlan @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DurationDays>k__BackingField")]
        public static extern ref int DurationDays(PricingPlan @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
        public static extern ref bool IsActive(PricingPlan @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(PricingPlan @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PlanType>k__BackingField")]
        public static extern ref PricingPlanType PlanType(PricingPlan @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Price>k__BackingField")]
        public static extern ref decimal Price(PricingPlan @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Asset>k__BackingField")]
        public static extern ref Asset Asset(PricingPlan @this);
    }
}
