// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Database.Abstractions;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class RoleBaseUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Display>k__BackingField")]
        public static extern ref string Display(RoleBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Enabel>k__BackingField")]
        public static extern ref bool Enabel(RoleBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(RoleBase @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Power>k__BackingField")]
        public static extern ref int Power(RoleBase @this);
    }
}
