// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Enums;
using Netor.Cortana.Platform.Entitys.Tables.Accounts;
using Netor.Cortana.Platform.Entitys.Tables.Assets;
using Netor.Cortana.Platform.Entitys.Tables.Orders;
using Netor.Cortana.Platform.Entitys.Tables.Subscriptions;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class SubscriptionUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AccountId>k__BackingField")]
        public static extern ref string AccountId(Subscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AssetId>k__BackingField")]
        public static extern ref string AssetId(Subscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CanceledAtUtc>k__BackingField")]
        public static extern ref DateTimeOffset? CanceledAtUtc(Subscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpiresAtUtc>k__BackingField")]
        public static extern ref DateTimeOffset ExpiresAtUtc(Subscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OrderId>k__BackingField")]
        public static extern ref string OrderId(Subscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PricingPlanId>k__BackingField")]
        public static extern ref string PricingPlanId(Subscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StartedAtUtc>k__BackingField")]
        public static extern ref DateTimeOffset StartedAtUtc(Subscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
        public static extern ref SubscriptionStatus Status(Subscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref Account Account(Subscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Asset>k__BackingField")]
        public static extern ref Asset Asset(Subscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Order>k__BackingField")]
        public static extern ref Order Order(Subscription @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PricingPlan>k__BackingField")]
        public static extern ref PricingPlan PricingPlan(Subscription @this);
    }
}
