// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Database.Abstractions;
using Netor.Database.Abstractions.Enums;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class SystemSettingUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Display>k__BackingField")]
        public static extern ref string Display(SystemSetting @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Group>k__BackingField")]
        public static extern ref string Group(SystemSetting @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsProtection>k__BackingField")]
        public static extern ref bool IsProtection(SystemSetting @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Key>k__BackingField")]
        public static extern ref string Key(SystemSetting @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(SystemSetting @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref NetorDataType Type(SystemSetting @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Value>k__BackingField")]
        public static extern ref string Value(SystemSetting @this);
    }
}
