// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Cortana.Platform.Entitys.Tables.Orders;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class TransactionUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OrderId>k__BackingField")]
        public static extern ref string OrderId(Transaction @this);
    }
}
