// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Database.Abstractions;
using Netor.Database.Abstractions.Interface;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class TransactionBaseUnsafeAccessors<TAccount>
        where TAccount : Base, IAccount
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Content>k__BackingField")]
        public static extern ref string Content(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Money>k__BackingField")]
        public static extern ref decimal Money(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<No>k__BackingField")]
        public static extern ref string No(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Numbers>k__BackingField")]
        public static extern ref int Numbers(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OrderNo>k__BackingField")]
        public static extern ref string OrderNo(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PayMethod>k__BackingField")]
        public static extern ref byte PayMethod(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PayStatus>k__BackingField")]
        public static extern ref byte PayStatus(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PayTime>k__BackingField")]
        public static extern ref DateTime? PayTime(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RealMoney>k__BackingField")]
        public static extern ref decimal RealMoney(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ThirdNo>k__BackingField")]
        public static extern ref string ThirdNo(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Title>k__BackingField")]
        public static extern ref string Title(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref byte Type(TransactionBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref TAccount Account(TransactionBase<TAccount> @this);
    }
}
