// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Netor.Database.Abstractions;
using Netor.Database.Abstractions.Interface;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Netor.Cortana.Platform.Entitys.Data.CompiledModels
{
    public static class WalletBaseUnsafeAccessors<TAccount>
        where TAccount : Base, IAccount
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Money>k__BackingField")]
        public static extern ref decimal Money(WalletBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(WalletBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Status>k__BackingField")]
        public static extern ref byte Status(WalletBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref byte Type(WalletBase<TAccount> @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Account>k__BackingField")]
        public static extern ref TAccount Account(WalletBase<TAccount> @this);
    }
}
