using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

using Netor.Cortana.AI.Workflow.Title;
using Netor.Cortana.Entitys;
using Netor.Cortana.Entitys.Services;
using Netor.EventHub;

namespace Netor.Cortana.AI.Workflow;

/// <summary>
/// 默认 <see cref="IWorkflowExecutor"/> 实现。
/// 阶段 2B 占位实现：仅打通数据库 + 事件路径，不接入真实 SDK Workflow。
///
/// 占位行为：
/// - StartTaskAsync：同步写一条 Task 记录（Pending → Running → Completed），
///   FinalReport = "[阶段 2B 占位] Workflow 子模式尚未实现，本任务仅打通基础设施。"
/// - 发送完整事件链：task.started → task.completed
/// - 不调用任何 LLM、不消耗 token
///
/// IHostedService：
/// - StartAsync：扫描 OrchestrationTask 表中 status 为 Running/Paused/Pending 的"内存中无 Run"
///   的孤儿任务，全部标记为 Failed（决策 9-A）。
///
/// 详见 docs/未来版本策划/多智能体编排模式策划/04-实施阶段.md §2B.4 / §2B.6。
/// </summary>
public sealed class WorkflowExecutor(
    WorkflowTaskRepository taskRepo,
    WorkflowStepRepository stepRepo,
    WorkflowExecutorOptions options,
    IWorkflowTitleGenerator titleGenerator,
    IPublisher publisher,
    ILogger<WorkflowExecutor> logger) : IWorkflowExecutor, IHostedService
{
    // ──── IHostedService：启动孤儿清理（决策 9-A） ────

    public Task StartAsync(CancellationToken cancellationToken)
    {
        try
        {
            var orphans = taskRepo.QueryByStatuses([
                WorkflowTaskStatus.Running.ToDbValue(),
                WorkflowTaskStatus.Paused.ToDbValue(),
                WorkflowTaskStatus.Pending.ToDbValue(),
            ]);

            if (orphans.Count == 0)
            {
                logger.LogDebug("WorkflowExecutor 启动孤儿扫描：无活跃任务遗留。");
                return Task.CompletedTask;
            }

            var now = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            foreach (var orphan in orphans)
            {
                taskRepo.UpdateCompleted(
                    orphan.Id,
                    status: WorkflowTaskStatus.Failed.ToDbValue(),
                    finalReport: null,
                    errorMessage: "宿主重启导致任务丢失，请重新启动该任务。",
                    completedAt: now,
                    lastActiveTimestamp: now);

                publisher.Publish(Events.OnWorkflowTaskFailed, new WorkflowTaskFailedArgs(
                    TaskId: orphan.Id,
                    SourceSessionId: orphan.SourceSessionId,
                    TraceId: orphan.TraceId,
                    WorkspaceId: orphan.WorkspaceId,
                    Mode: orphan.Mode,
                    SubMode: orphan.SubMode,
                    OccurredAt: DateTimeOffset.UtcNow,
                    Title: orphan.Title ?? string.Empty,
                    ErrorMessage: "宿主重启导致任务丢失",
                    FailureReason: "host_restart_orphan",
                    FailedAt: now));
            }

            publisher.Publish(Events.OnSystemNotice, new SystemNoticeArgs(
                Content: $"检测到 {orphans.Count} 个 Workflow 任务因上次宿主重启中断，已标记为失败。" +
                         "可在工作台查看详情或使用「复制为新任务」功能重新启动。",
                Title: "Workflow 任务恢复",
                Level: "warning",
                Source: "WorkflowExecutor",
                CreatedAt: DateTimeOffset.Now));

            logger.LogWarning("WorkflowExecutor 启动孤儿扫描：清理 {Count} 个遗留任务。", orphans.Count);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "WorkflowExecutor 启动孤儿扫描失败");
        }

        return Task.CompletedTask;
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    // ──── 任务生命周期（阶段 2B 占位实现） ────

    public Task<string> StartTaskAsync(WorkflowTaskRequest request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        var taskId = Guid.NewGuid().ToString("N");
        var nowMs = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        var traceId = string.IsNullOrEmpty(request.TraceId)
            ? Guid.NewGuid().ToString("N")
            : request.TraceId;

        // 1. 写 OrchestrationTask 表（Pending → Running）
        var entity = new OrchestrationTaskEntity
        {
            Id = taskId,
            Title = string.IsNullOrWhiteSpace(request.Title) ? string.Empty : request.Title!,
            Summary = request.Summary ?? string.Empty,
            IsTitleAutoGenerated = string.IsNullOrWhiteSpace(request.Title),
            Mode = request.Mode,
            SubMode = request.SubMode,
            Status = WorkflowTaskStatus.Running.ToDbValue(),
            StartedAt = nowMs,
            LastActiveTimestamp = nowMs,
            TraceId = traceId,
            CreatedBy = request.CreatedBy,
            SourceSessionId = request.SourceSessionId,
            SourceTaskId = request.SourceTaskId,
            ManagerAgentId = request.ManagerAgentId,
            ManagerAgentName = request.ManagerAgentName,
            InitialInput = request.InitialInput,
            InitialAttachmentsJson = request.InitialAttachmentsJson,
            WorkspaceId = request.WorkspaceId,
            OverridesJson = request.OverridesJson,
        };
        taskRepo.Insert(entity);

        // 2. 写参与者（Manager + Members）
        if (!string.IsNullOrEmpty(request.ManagerAgentId))
        {
            stepRepo.InsertParticipant(new OrchestrationParticipantEntity
            {
                TaskId = taskId,
                AgentId = request.ManagerAgentId!,
                AgentName = request.ManagerAgentName ?? string.Empty,
                Role = "manager",
                JoinedAt = nowMs,
            });
        }
        foreach (var memberId in request.MemberAgentIds)
        {
            stepRepo.InsertParticipant(new OrchestrationParticipantEntity
            {
                TaskId = taskId,
                AgentId = memberId,
                AgentName = string.Empty,
                Role = "member",
                JoinedAt = nowMs,
            });
        }

        // 3. 发 task.started 事件
        var participantIds = new List<string>();
        if (!string.IsNullOrEmpty(request.ManagerAgentId)) participantIds.Add(request.ManagerAgentId!);
        participantIds.AddRange(request.MemberAgentIds);

        publisher.Publish(Events.OnWorkflowTaskStarted, new WorkflowTaskStartedArgs(
            TaskId: taskId,
            SourceSessionId: request.SourceSessionId,
            TraceId: traceId,
            WorkspaceId: request.WorkspaceId,
            Mode: request.Mode,
            SubMode: request.SubMode,
            OccurredAt: DateTimeOffset.UtcNow,
            Title: entity.Title,
            ManagerAgentId: request.ManagerAgentId,
            ManagerAgentName: request.ManagerAgentName,
            InitialInput: request.InitialInput,
            ParticipantAgentIds: participantIds,
            StartedAt: nowMs));

        // 4. 占位实现：立即标完成 + 发 task.completed 事件
        const string placeholderReport =
            "[阶段 2B 占位] Workflow 子模式尚未实现，本任务仅打通基础设施。\n\n" +
            "阶段 3B 起将接入真实 SDK Workflow（GroupChat / Magentic / ParallelAnalysis）。";

        var completedAtMs = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        taskRepo.UpdateCompleted(
            taskId,
            status: WorkflowTaskStatus.Completed.ToDbValue(),
            finalReport: placeholderReport,
            errorMessage: null,
            completedAt: completedAtMs,
            lastActiveTimestamp: completedAtMs);

        publisher.Publish(Events.OnWorkflowTaskCompleted, new WorkflowTaskCompletedArgs(
            TaskId: taskId,
            SourceSessionId: request.SourceSessionId,
            TraceId: traceId,
            WorkspaceId: request.WorkspaceId,
            Mode: request.Mode,
            SubMode: request.SubMode,
            OccurredAt: DateTimeOffset.UtcNow,
            Title: entity.Title,
            ManagerAgentId: request.ManagerAgentId,
            ManagerAgentName: request.ManagerAgentName,
            FinalReport: placeholderReport,
            StepCount: 0,
            TotalDurationMs: completedAtMs - nowMs,
            TotalTokenInputCount: 0,
            TotalTokenOutputCount: 0,
            ParticipantAgentIds: participantIds,
            CompletedAt: completedAtMs));

        // 5. 阶段 2B 占位不调用真实 LLM，所以也不触发标题兜底
        //    （titleGenerator 仅作为字段保留，阶段 3B 起在真实编排链路里调用）
        _ = titleGenerator;
        _ = options;

        logger.LogInformation(
            "Workflow 任务已创建（阶段 2B 占位）：taskId={TaskId}, mode={Mode}, subMode={SubMode}",
            taskId, request.Mode, request.SubMode);

        return Task.FromResult(taskId);
    }

    public Task<bool> CancelTaskAsync(string taskId, CancellationToken cancellationToken)
    {
        if (string.IsNullOrEmpty(taskId)) return Task.FromResult(false);

        // 阶段 2B 占位：任务都是同步立即完成的，没有 running 中状态可取消。
        // 但保留语义：如果状态是 Running 则置为 Cancelled。
        var task = taskRepo.GetById(taskId);
        if (task is null) return Task.FromResult(false);

        var status = WorkflowTaskStatusExtensions.FromDbValue(task.Status);
        if (status is WorkflowTaskStatus.Running or WorkflowTaskStatus.Paused or WorkflowTaskStatus.Pending)
        {
            var now = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            taskRepo.UpdateCompleted(
                taskId,
                status: WorkflowTaskStatus.Cancelled.ToDbValue(),
                finalReport: task.FinalReport,
                errorMessage: "用户取消",
                completedAt: now,
                lastActiveTimestamp: now);

            publisher.Publish(Events.OnWorkflowTaskFailed, new WorkflowTaskFailedArgs(
                TaskId: taskId,
                SourceSessionId: task.SourceSessionId,
                TraceId: task.TraceId,
                WorkspaceId: task.WorkspaceId,
                Mode: task.Mode,
                SubMode: task.SubMode,
                OccurredAt: DateTimeOffset.UtcNow,
                Title: task.Title ?? string.Empty,
                ErrorMessage: "用户取消",
                FailureReason: "cancelled",
                FailedAt: now));

            return Task.FromResult(true);
        }

        return Task.FromResult(false);
    }

    public Task<WorkflowTaskStatus> GetTaskStatusAsync(string taskId, CancellationToken cancellationToken)
    {
        var task = taskRepo.GetById(taskId);
        return Task.FromResult(task is null
            ? WorkflowTaskStatus.Failed
            : WorkflowTaskStatusExtensions.FromDbValue(task.Status));
    }

    // ──── 任务列表与浏览 ────

    public Task<IReadOnlyList<OrchestrationTaskEntity>> ListTasksAsync(
        WorkflowTaskListQuery query,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(query);
        var list = taskRepo.ListByWorkspace(
            query.WorkspaceId,
            query.IncludeArchived,
            query.Statuses,
            query.Limit,
            query.Offset);
        return Task.FromResult<IReadOnlyList<OrchestrationTaskEntity>>(list);
    }

    public Task<OrchestrationTaskDetail?> GetTaskDetailAsync(string taskId, CancellationToken cancellationToken)
    {
        var task = taskRepo.GetById(taskId);
        if (task is null) return Task.FromResult<OrchestrationTaskDetail?>(null);

        var status = WorkflowTaskStatusExtensions.FromDbValue(task.Status);

        var detail = new OrchestrationTaskDetail
        {
            Task = task,
            Participants = stepRepo.GetParticipantsByTask(taskId),
            Steps = stepRepo.GetStepsByTask(taskId),
            Messages = stepRepo.GetMessagesByTask(taskId),
            IsLive = status is WorkflowTaskStatus.Running or WorkflowTaskStatus.Paused,
            CanCancel = status is WorkflowTaskStatus.Running or WorkflowTaskStatus.Paused or WorkflowTaskStatus.Pending,
            CanDuplicate = status is WorkflowTaskStatus.Completed or WorkflowTaskStatus.Failed or WorkflowTaskStatus.Cancelled,
        };

        return Task.FromResult<OrchestrationTaskDetail?>(detail);
    }

    // ──── 列表元数据操作 ────

    public Task SetPinnedAsync(string taskId, bool pinned, CancellationToken cancellationToken)
    {
        taskRepo.SetPinned(taskId, pinned);
        return Task.CompletedTask;
    }

    public Task SetArchivedAsync(string taskId, bool archived, CancellationToken cancellationToken)
    {
        taskRepo.SetArchived(taskId, archived);
        return Task.CompletedTask;
    }

    public Task RenameTitleAsync(string taskId, string newTitle, CancellationToken cancellationToken)
    {
        if (string.IsNullOrEmpty(taskId)) return Task.CompletedTask;
        var task = taskRepo.GetById(taskId);
        if (task is null) return Task.CompletedTask;

        var oldTitle = task.Title ?? string.Empty;
        taskRepo.UpdateTitle(taskId, newTitle ?? string.Empty, isAutoGenerated: false);

        publisher.Publish(Events.OnWorkflowTaskTitleUpdated, new WorkflowTaskTitleUpdatedArgs(
            TaskId: taskId,
            SourceSessionId: task.SourceSessionId,
            TraceId: task.TraceId,
            WorkspaceId: task.WorkspaceId,
            Mode: task.Mode,
            SubMode: task.SubMode,
            OccurredAt: DateTimeOffset.UtcNow,
            OldTitle: oldTitle,
            NewTitle: newTitle ?? string.Empty,
            IsAutoGenerated: false));

        return Task.CompletedTask;
    }

    public Task DeleteTaskAsync(string taskId, CancellationToken cancellationToken)
    {
        taskRepo.Delete(taskId);
        return Task.CompletedTask;
    }

    // ──── 复制为新任务（决策 10-A） ────

    public Task<WorkflowTaskRequest> BuildRequestFromTemplateAsync(
        string sourceTaskId,
        CancellationToken cancellationToken)
    {
        var source = taskRepo.GetById(sourceTaskId)
            ?? throw new InvalidOperationException($"Source task not found: {sourceTaskId}");

        // 收集 Member Agent Ids
        var participants = stepRepo.GetParticipantsByTask(sourceTaskId);
        var memberIds = participants
            .Where(p => p.Role == "member")
            .Select(p => p.AgentId)
            .ToList();

        return Task.FromResult(new WorkflowTaskRequest
        {
            Title = null,                                 // 留空，让 LLM 兜底
            Summary = source.Summary,
            Mode = source.Mode,
            SubMode = source.SubMode,
            InitialInput = source.InitialInput,
            InitialAttachmentsJson = source.InitialAttachmentsJson,
            WorkspaceId = source.WorkspaceId,
            CreatedBy = "duplicated",
            SourceSessionId = source.SourceSessionId,
            SourceTaskId = sourceTaskId,                  // 记录原任务（决策 10-A）
            TraceId = null,                                // 新 traceId
            ManagerAgentId = source.ManagerAgentId,
            ManagerAgentName = source.ManagerAgentName,
            MemberAgentIds = memberIds,
            OverridesJson = source.OverridesJson,
        });
    }
}
