namespace Madorin.AI.Runtime.Persistence.Abstractions;

public sealed record ToolGrantState(
    string GrantId,
    string RunId,
    string? AgentId,
    string? ParentGrantId,
    string RootGrantId,
    string WorkspaceRoot,
    string[] AllowedToolIds,
    string[] AllowedCallIds,
    int MaximumRisk,
    string[] AllowedReadRoots,
    string[] AllowedWriteRoots,
    bool AllowOverwrite,
    bool AllowMove,
    bool AllowDelete,
    string[] AllowedExecutables,
    string[] AllowedEnvironmentVariables,
    bool AllowPowerShell,
    string NetworkPolicyJson,
    DateTimeOffset ExpiresAt,
    bool AllowDelegation,
    string[] DelegatedAgentIds,
    string[] DelegationChain,
    DateTimeOffset CreatedAt,
    DateTimeOffset? RevokedAt = null,
    string? RevocationReason = null,
    string? ApprovalRequestId = null);
