using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;

using Netor.Cortana.Plugin.Process.Generator.Analysis;

namespace Netor.Cortana.Plugin.Process.Generator.Emitters;

/// <summary>
/// 生成 <c>{PluginClass}Debugger.g.cs</c>：
/// 每个 [Plugin] 类会对应一个 Debugger 类，
/// 暴露所有 [Tool] 方法的强类型 <c>InvokeXxxAsync(...)</c> 包装，
/// 用户写单元测试时无需手动构造 JSON。
/// </summary>
internal static class DebuggerEmitter
{
    public static string Emit(PluginClassInfo plugin, List<ToolClassInfo> toolClasses)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// 由 Netor.Cortana.Plugin.Process.Generator 自动生成");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        if (plugin.Namespace != null)
        {
            sb.AppendLine($"namespace {plugin.Namespace};");
            sb.AppendLine();
        }

        var debuggerName = plugin.ClassName + "Debugger";

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// <c>{plugin.ClassName}</c> 的强类型调试器，由 Generator 生成。");
        sb.AppendLine("/// 通过内存管道驱动同一消息循环，暴露所有 [Tool] 方法的直接调用包装。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed class {debuggerName} : global::Netor.Cortana.Plugin.Process.Debugging.PluginDebugger");
        sb.AppendLine("{");
        sb.AppendLine($"    private {debuggerName}()");
        sb.AppendLine($"        : base({plugin.ClassName}.RunPluginAsync) {{ }}");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>创建新的调试器实例并启动插件消息循环。</summary>");
        sb.AppendLine($"    public static {debuggerName} Create() => new();");
        sb.AppendLine();

        foreach (var toolClass in toolClasses)
        {
            foreach (var method in toolClass.Methods)
                EmitToolMethod(sb, method);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitToolMethod(StringBuilder sb, ToolMethodInfo method)
    {
        var methodName = method.MethodName; // 直接用用户定义的方法名，最易读
        if (!methodName.EndsWith("Async"))
            methodName += "Async";

        sb.AppendLine($"    /// <summary>调用工具 <c>{method.FullToolName}</c>。返回值为工具原始字符串输出。</summary>");
        if (!string.IsNullOrEmpty(method.Description))
            sb.AppendLine($"    /// <remarks>{method.Description}</remarks>");

        var paramSig = string.Join(", ",
            method.Parameters.Select(p => $"{p.TypeSymbol.ToDisplayString()} {p.CodeParamName}"));

        sb.AppendLine($"    public global::System.Threading.Tasks.Task<string> {methodName}({paramSig})");
        sb.AppendLine("    {");

        if (method.Parameters.Count == 0)
        {
            sb.AppendLine("        var args = global::Netor.Cortana.Plugin.Process.Debugging.DebuggerArgs.Build();");
        }
        else
        {
            sb.AppendLine("        var args = global::Netor.Cortana.Plugin.Process.Debugging.DebuggerArgs.Build()");
            for (int i = 0; i < method.Parameters.Count; i++)
            {
                var p = method.Parameters[i];
                var isLast = i == method.Parameters.Count - 1;
                var suffix = isLast ? ";" : "";
                if (TypeMapper.IsNullableValueType(p.TypeSymbol))
                {
                    sb.AppendLine($"            .AddIfNotNull(\"{p.JsonName}\", {p.CodeParamName}){suffix}");
                }
                else
                {
                    sb.AppendLine($"            .Add(\"{p.JsonName}\", {p.CodeParamName}){suffix}");
                }
            }
        }

        sb.AppendLine($"        return InvokeAsync(\"{method.FullToolName}\", args);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
